### ISSUE TITLE
Invalid Argument Exception

### ISSUE THREAD

**Issue by smockensturm** [flipboxfactory/saml-sp#10]
Hi. Installation fails.

`composer require flipboxfactory/saml-sp
`
> Could not find a version of package flipboxfactory/saml-sp matching your minimum-stability (stable). Require it with an explicit version constraint allowing its desired stability.

Please advise. Thanks.

Craft CMS 3.0.18
PHP 7.0
Composer 1.6.4

**Comment by nateiler** [comment]
The plugin isn't technically in a stable release yet.  Therefore you'll need to add this to your `composer.json` file:

```
"minimum-stability":"beta",
"prefer-stable": true
```

**Comment by smockensturm** [comment]
Thanks. All set.
