### ISSUE TITLE
2.6.6 Update Information Missing

### ISSUE THREAD

**Issue by stidmore** [flipboxfactory/saml-sp#105]
When viewing available updates in the Craft CP, it shows an update for 2.6.6 under SAML Service Provider, but there is no date associated with it and no information on the update. That update isn't listed in your changelog in GitHub, but I do see the version number change in this commit https://github.com/flipboxfactory/saml-sp/commit/2995a6d5c84ac4daeb4a1f2f9de41bab295141a9.

Is that a legitimate update? Right now it looks a bit suspicious in the control panel.

![Screen Shot 2021-04-06 at 8 29 06 AM](https://user-images.githubusercontent.com/1612964/113720809-9d2a3200-96b4-11eb-9031-df7244119707.png)

**Comment by dsmrt** [comment]
Yep! that is legit! I bumped the version to force update the saml-core lib.

It might not have been notable enough for the changelog update.
