### ISSUE TITLE
Server error in Craft after redirect from Google IDP

### ISSUE THREAD

**Issue by rostockahoi** [flipboxfactory/saml-sp#107]
Hi there,
I have an error with Google SSO.

# What happens
- click on login in Craft
- redirect to Google login
- login
- redirect back to Craft
- 500 server error in Craft

# Fix
I am able to fix the error and everything works just fine by putting the following line above [User.php:145](https://github.com/flipboxfactory/saml-sp/blob/2995a6d5c84ac4daeb4a1f2f9de41bab295141a9/src/services/login/User.php#L145):
`$user->email = $user->usename;`

I feel like I am missing some configuration, do I?

# Exception output

- Translation: "E-Mail darf nicht leer sein." => "Email must not be empty."

```
2021-04-09 18:42:42 [-][-][86nq472enlj7bpklnsff7ehglf][error][saml-sp] User save failed: {"email":["E-Mail darf nicht leer sein."]}
2021-04-09 18:42:42 [-][-][86nq472enlj7bpklnsff7ehglf][error][yii\base\UserException] yii\base\UserException: User save failed: {"email":["E-Mail darf nicht leer sein."]} in /path/to/craft/vendor/flipboxfactory/saml-sp/src/services/login/User.php:172
Stack trace:
#0 /path/to/craft/vendor/flipboxfactory/saml-sp/src/services/login/User.php(145): flipbox\saml\sp\services\login\User->save()
#1 /path/to/craft/vendor/flipboxfactory/saml-sp/src/services/Login.php(68): flipbox\saml\sp\services\login\User->sync()
#2 /path/to/craft/vendor/flipboxfactory/saml-sp/src/controllers/LoginController.php(112): flipbox\saml\sp\services\Login->transformToUser()
#3 [internal function]: flipbox\saml\sp\controllers\LoginController->actionIndex()
#4 /path/to/craft/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#5 /path/to/craft/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams()
#6 /path/to/craft/vendor/craftcms/cms/src/web/Controller.php(190): yii\base\Controller->runAction()
#7 /path/to/craft/vendor/yiisoft/yii2/base/Module.php(534): craft\web\Controller->runAction()
#8 /path/to/craft/vendor/craftcms/cms/src/web/Application.php(274): yii\base\Module->runAction()
#9 /path/to/craft/vendor/yiisoft/yii2/web/Application.php(104): craft\web\Application->runAction()
#10 /path/to/craft/vendor/craftcms/cms/src/web/Application.php(259): yii\web\Application->handleRequest()
#11 /path/to/craft/vendor/yiisoft/yii2/base/Application.php(392): craft\web\Application->handleRequest()
#12 /path/to/craft/web/index.php(21): yii\base\Application->run()
#13 {main}
```

**Comment by dsmrt** [comment]
:wave: @rostockahoi

Do you have email mapping configured on the IdP Edit page?

I have one instance mapped from the Google side like this: 
![Screen Shot 2021-04-09 at 11 41 41 AM](https://user-images.githubusercontent.com/1995478/114219998-aae7ed80-9928-11eb-907a-9a9e9be6de9b.png)

Then from the Craft side like this:
![Screen Shot 2021-04-09 at 11 43 24 AM](https://user-images.githubusercontent.com/1995478/114220122-d23eba80-9928-11eb-88c6-dcd13a1864d7.png)

**Comment by rostockahoi** [comment]
Works like a charm, thank's a lot for that fast response.
