### ISSUE TITLE
Copy to clipboard doesn't work

### ISSUE THREAD

**Issue by darylknight** [flipboxfactory/saml-sp#113]
I'm just working with the plugin for the first time and run into a couple of issues. First minor one; the copy to clipboard function doesn't seem to work on admin/saml-sp/metadata/2#metadata:

![image](https://user-images.githubusercontent.com/1250017/118230841-ebdaa100-b496-11eb-92f6-19c2d22afab8.png)

When I paste into VSCode, my clipboard has what it did before clicking that button.

**Comment by dsmrt** [comment]
👋 @darylknight ,

I added the patch. Let me know if you are still seeing issues.

**Comment by darylknight** [comment]
Excellent, thank you! Looks like it's working now.
