### ISSUE TITLE
Settings shouldn't be available on Project Config sites

### ISSUE THREAD

**Issue by darylknight** [flipboxfactory/saml-sp#114]
I just went to change the Default Entity ID on our staging server and got the standard 'changes can't be made while allowAdminChanges is false' error, on admin/saml-sp/settings

If this is controlled by project config, it should either be hidden in environments where changes aren't allowed, or set to 'read only'

![image](https://user-images.githubusercontent.com/1250017/118232323-09a90580-b499-11eb-8af8-d62d5c2e5413.png)

**Comment by dsmrt** [comment]
👋 @darylknight 

good call. I’ll take a look

**Comment by dsmrt** [comment]
Patched the saml-core package that manages this area. Update this plugin package and you should se this fixed.
