### ISSUE TITLE
IDP Per User Group

### ISSUE THREAD

**Issue by masonry47** [flipboxfactory/saml-sp#124]
Hi there!  We are wondering what the feasibility is of authenticating front end users with a different IDP than a CP author?  

Thanks in advance for any thoughts you might have on that!

**Comment by dsmrt** [comment]
👋 @masonry47,

I want some clarity on the question.

Sounds like you may want to break up the authentication/authorization based on different IdPs and maybe treat those as groups within Craft. 

Might look like this (these are examples I'm coming up with on the fly here): 

IdP no. 1: From Azure AD IdP a set of users login and are assigned to the user group for "authors" in Craft.
IdP no. 2: From Okta IdP a set of users login and are assigned to the user group for "end users" in Craft.
... and so on.

Is this what you are trying to do?

If so, know that you can have multiple IdPs connected to the Craft instance/SSO plugin. Assigning groups automatically based on the that "attribute" (of being from a specific IdP) is probably a custom event. See events docs: https://saml-sp.flipboxfactory.com/configure/events.html#examples

**Comment by masonry47** [comment]
Hey @dsmrt 

Thanks for this.  The scenario you describe is exactly what we would be trying to do.  It does sound like it is feasible then??

Thanks again!

**Comment by dsmrt** [comment]
Yes. Look at these examples: https://saml-sp.flipboxfactory.com/configure/events.html#examples

You'd probably want to run some code based on the Issuer within the Response message from the IdP. The Issuer is essentially the IdP EntityId.

The Response is attached to the `UserLogin` event (https://github.com/flipboxfactory/saml-sp/blob/master/src/events/UserLogin.php#L27). You can add something like this within the our UserLogin event example:

```php
switch($event->response->getIssuer()->getValue()){
    case 'https://1-idp.example.com':
        // add to user group a
        break;
    case 'https://2-idp.example.com':
        // add to user group b
        break;
}
```

Does this make sense?

**Comment by masonry47** [comment]
Thanks!  I think it makes sense.  One thing to be clear is there is not multiple domains (the example above shows a conditional based on 2 different domains).

There are just 2 different sets of users...Craft Authors (Azure) & Front End users (A Drupal Instance setup as an IDP).

Thanks again for you thoughts on this!

**Comment by dsmrt** [comment]
Yep. That makes sense. To be clear (from my side), the issuer/entity id is usually represented as a URL but it can be another type of string like a uuid. So, the example above shows multiple domains but those are really more of unique ids for the IdPs than anything.

Let me know if you need me to elaborate on this.

**Comment by masonry47** [comment]
Thank you!

**Comment by dsmrt** [comment]
Closing this for now. Let me know if you need anything else!
