### ISSUE TITLE
Upgrade Issue - getDefaultLogoutRequestEndpoint

### ISSUE THREAD

**Issue by AANP-ITSupport** [flipboxfactory/saml-sp#125]
We recently updated our QA Environment from Craft Pro 3.5.15.1 to Craft Pro 3.7.7

Then updated the SAML Plugin from 2.5.2 to 2.6.9.

The plugin is mostly working except for one item.  If I manually enter the SSO Logout URL (/sso/logout/request) then I am logged out successfully.

But we had been using a configuration property for that URL, based on the Issue here:

https://github.com/flipboxfactory/saml-sp/issues/8 
https://github.com/flipboxfactory/saml-sp/issues/9

So now, it appears that the samlSp.settings.getDefaultLogoutRequestEndpoint property no longer returns the expected path.

How should we identify the logout path moving forward?  Updating the general.php logoutPath value with what I see in the admin tool for the logout endpoint url?

**Comment by dsmrt** [comment]
Looking into this now.

**Comment by dsmrt** [comment]
Some of those endpoints changed with 2.6.0: https://github.com/flipboxfactory/saml-sp/blob/master/CHANGELOG.md#260---2021-01-08. I moved some of those out of the settings (which didn't make as much sense) to the provider record.

You can use `provider.getLogoutRequestEndpoint`. There's an example in the login.twig page that shows how to loop through providers here: https://github.com/flipboxfactory/saml-sp/blob/23629c4c3e4b6dff7a453290df7404c373c2b7a5/src/templates/_cp/login.twig#L92-L100

Obviously you'd switch out `getLoginRequestPath` with `getLogoutRequestPath`.

Furthermore, you can see some more helper provider queries here (in same-core): 

https://github.com/flipboxfactory/saml-core/blob/master/src/services/AbstractProviderService.php

Let me know if you need any help with the query.

**Comment by AANP-ITSupport** [comment]
Thanks for the clarification and references, appreciated.
