### ISSUE TITLE
Signature required but not found: Response

### ISSUE THREAD

**Issue by nickdunn** [flipboxfactory/saml-sp#128]
Plugin has been working until today when I'm receiving this when logging in after deploying the site (project-config did its thing and updated the various site sections etc)

```
Exception: Signature required but not found: Response in /var/www/craft/vendor/flipboxfactory/saml-sp/src/validators/SignedElement.php:51
Stack trace:
#0 /var/www/craft/vendor/flipboxfactory/saml-sp/src/validators/Response.php(86): flipbox\saml\sp\validators\SignedElement->validate(Object(SAML2\Response), Object(SAML2\Response\Validation\Result))
#1 /var/www/craft/vendor/flipboxfactory/saml-sp/src/controllers/LoginController.php(111): flipbox\saml\sp\validators\Response->validate(Object(SAML2\Response))
#2 [internal function]: flipbox\saml\sp\controllers\LoginController->actionIndex('77a2e32b-64fd-4...')
#3 /var/www/craft/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#4 /var/www/craft/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#5 /var/www/craft/vendor/craftcms/cms/src/web/Controller.php(190): yii\base\Controller->runAction('', Array)
#6 /var/www/craft/vendor/yiisoft/yii2/base/Module.php(534): craft\web\Controller->runAction('', Array)
#7 /var/www/craft/vendor/craftcms/cms/src/web/Application.php(277): yii\base\Module->runAction('saml-sp/login', Array)
#8 /var/www/craft/vendor/yiisoft/yii2/web/Application.php(104): craft\web\Application->runAction('saml-sp/login', Array)
#9 /var/www/craft/vendor/craftcms/cms/src/web/Application.php(262): yii\web\Application->handleRequest(Object(craft\web\Request))
#10 /var/www/craft/vendor/yiisoft/yii2/base/Application.php(392): craft\web\Application->handleRequest(Object(craft\web\Request))
#11 /var/www/craft/web/index.php(22): yii\base\Application->run()
#12 {main}
```

Any idea what might be going on?

Craft: 3.7.13
Plugin: 2.7.0

**Comment by dsmrt** [comment]
This has todo with some possible security issues exposed here: #126
This error means that the IdP is not sending a signed response. I hope they are sending a signed assertion or that the assertions are encrypted. 

You can bypass this by adding `requireResponseToBeSigned` or `requireAssertionToBeSigned` to the `config/saml-sp.php` like so:

`config/saml-sp.php`
```php
return [
'requireResponseToBeSigned'=>false, // try adding this first, without the below
// OR / AND
'requireAssertionToBeSigned'=> false,
];
```

Ultimately, you should get the response and assertion signed from the IdP, so if you do bypass this using the new setting, work to get the IdP signing them soon.

**Comment by nickdunn** [comment]
Thanks for the quick reply! We're using Azure AD so I would expect it to be signed and/or encrypted?

**Comment by nickdunn** [comment]
Thanks for the quick reply! We're using Azure AD so I would expect it to be signed and/or encrypted?

**Comment by dsmrt** [comment]
In that case (with Azure AD), looks like the assertion should be signed by default (so that's really good and maybe you only have to add the `'requireResponseToBeSigned'=>false` to the config:
https://docs.microsoft.com/en-us/azure/active-directory/manage-apps/certificate-signing-options#certificate-signing-options

**Comment by nickdunn** [comment]
Yep back and working again just using `'requireResponseToBeSigned' => false`.

Not sure why, but when I updated the extension in Craft the changelog description was blank for 2.7.0 so I didn't see the breaking change warning.

Thanks for helping us resolve it so quickly.

**Comment by dsmrt** [comment]
@nickdunn, looks like the changelog might have been formatted incorrectly resulting it the warning not showing like I was hoping. I apologize for that but I'm glad it working now.
