### ISSUE TITLE
User account creation automatic?

### ISSUE THREAD

**Issue by lamboap** [flipboxfactory/saml-sp#129]
Installing the plug-in for Okta integration.  I had a question around how the assertion is done.  Do we need accounts pre-created on CraftCMS for the assertion to work or can CraftCMS create accounts if the request is coming from a trusted source?  Is it possible to have Okta solely be the entry point into our instance of CraftCMS?

**Comment by dsmrt** [comment]
:wave: @lamboap ,

By default, the plugin will create the user accounts if one is not found. I can go into more info here if you'd like but here are some good resources to get started:

Getting setup with Okta (this is done on an older version of the plugin but should still be relevant):
https://www.flipboxdigital.com/insights/configuring-saml-sp-with-okta-com

The video on the page is pretty helpful if you want to follow along. It's for Azure AD but Okta has similar stuff going on:
https://saml-sp.flipboxfactory.com/idps/azure-ad.html

**Comment by lamboap** [comment]
thanks.  we've just gotten a license and am working through integration.

**Comment by dsmrt** [comment]
Sounds good! Let me know how it goes or if you need help with anything.
