### ISSUE TITLE
Add RelayState override 

### ISSUE THREAD

**Issue by dsmrt** [flipboxfactory/saml-sp#13]
Add the ability to override the RelayState. 

An example would be a button like so:
```php
<a href="{{ loginUrl }}?RelayState=/my/area">Login</a>
```
That get variable will be used to override any other logic to obtain a relay state.

**Comment by nateiler** [comment]
My vote is to make this GET variable configurable via the plugin settings.  In one case it may be 'RelayState' another may be 'redirect', etc.

**Comment by nateiler** [comment]
This is work around:

```{% requireLogin %}

{% set redirectUrl = craft.app.request.getParam('relayState') %}

{% redirect redirectUrl 302 %}```

**Comment by dsmrt** [comment]
Added in [1.0.0-beta.14](https://github.com/flipboxfactory/saml-sp/tree/1.0.0-beta.14).
You can pass the param as suggested and it will override the craft return url by passing the default parameter `RelayState` or you can change that name by adding `relayStateOverrideParam` to your `config/saml-sp.php`.
