### ISSUE TITLE
How to map roles to group

### ISSUE THREAD

**Issue by hiasl** [flipboxfactory/saml-sp#132]
Upfront: I'm a SAML newbie, and/but I managed to connect Craft to our IDP. Users are created correctly, username, first, last and e-mail are assigned as well. But I have problems assigning the correct user groups:

At the moment I have 2 relevant user groups which I want to assign via SAML-SP:
- "Content Editors" with handle "contentEditors"
- Admins (This is not a usergroup, it's the Admin flag of a user)

I am trying to map this XML response to those 2 cases:
```
<saml2:Attribute FriendlyName="ROLES" Name="urn:oid:1.2.40.0.10.2.1.1.261.30" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri">
   <saml2:AttributeValue>access();contentEditors()</saml2:AttributeValue>
</saml2:Attribute>
```

I tried a `config/saml-sp.php` with the following content (I also tried all 3 options as only items in the Array):
```
return [
    'groupAttributeNames' => [
        'roles',
        'ROLES',
        'urn:oid:1.2.40.0.10.2.1.1.261.30',
    ],
];
```

My questions: 
- Is groupAttributeNames the correct config key?
- If yes, what do I need to enter there to get it working with my XML
- How do I assign the admin flag?

Thanks for your help!

**Comment by dsmrt** [comment]
:wave: @hiasl,

Honestly, as a newbie to SAML, sounds like you're doing great! SAML can be confusing :/

q1) Try making the config like this: 
```php
return [
    'groupAttributeNames' => [
        'urn:oid:1.2.40.0.10.2.1.1.261.30', // this is the name value
    ],
];
```
q2)
Then the values of the `AttributeValue` should match the handle of the Craft User Group. Something like the following can come over as shown below. Note the attribute value can be an array like shown.
```xml
<saml2:Attribute FriendlyName="ROLES" Name="urn:oid:1.2.40.0.10.2.1.1.261.30" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri">
   <saml2:AttributeValue>contentEditors</saml2:AttributeValue>
   <saml2:AttributeValue>admins</saml2:AttributeValue>
</saml2:Attribute>
```
q3)
There's no way to add an admin flag via attributes coming over the XML so I'd suggest either 1) creating an admin user group and using that group to be passed over as one of the groups OR 2) adding a event to manage these users as needed (See https://saml-sp.flipboxfactory.com/configure/events.html#assign-user-to-a-user-group-based-on-a-property).

Ultimately, if the group assignment isn't working like you need it to take a look at the events like mentioned above (https://saml-sp.flipboxfactory.com/configure/events.html#assign-user-to-a-user-group-based-on-a-property).

Does this help clear things up?

**Comment by hiasl** [comment]
Hi @dsmrt,
thanks for your quick reply. I already tried this:
```
return [
    'groupAttributeNames' => [
        'urn:oid:1.2.40.0.10.2.1.1.261.30', // this is the name value
    ],
];
```
It did not work, but I guess this is because of the semi-colon separated format the roles are returned and also the parenthesis at the end of each role:
`   <saml2:AttributeValue>access();contentEditors()</saml2:AttributeValue>`

So it seems I need to go the EVENT way you pointed me to, which also is a solution to the admin flag. What the example does not explain however is how I can access the XML attributes of the SAML response from the IDP. How can I get my "role" attribute from within the Event? (this `access();contentEditors()` in the sample above, or in other words, the `urn:oid:1.2.40.0.10.2.1.1.261.30` value).

**Comment by dsmrt** [comment]
Yes, since `access();contentEditors()` as a string doesn't match the handle of a group, it's not getting picked up.

Seems like the using the event is the way to go. 

Here is example on how to interact with the Response > Assertion > Attributes. Note that if the assertions are encrypted this gets a little more complicated (let me know if that is the case).

```php
        Event::on(
            \flipbox\saml\sp\services\Login::class,
            \flipbox\saml\sp\services\Login::EVENT_AFTER_RESPONSE_TO_USER,
            function (\flipbox\saml\sp\events\UserLogin $event) {

                /** @var \craft\elements\User $user */
                $user = $event->user;
                /** @var \SAML2\Response $response */
                $response = $event->response;

                // This only works when the assertion is not encrypted
                $assertions = $response->getAssertions();
                foreach($assertions as $assertion) {
                    foreach ($assertion->getAttributes() as $attributeName => $attributeValue) {
                        // look for your group attribute name and do what you need to do here
                        \Craft::debug([$attributeName, $attributeValue]);
                    }
                }
            }
        );
```

FYI, the plugin has pretty good debug logging. You can run something like this: `tail -f storage/logs/web.log | grep -A 10 '\[saml-'` to view the logs easier.

**Comment by hiasl** [comment]
Guess what, I have a Jackpot setup here :-) Of course assertions are encrypted.
Although I was 99% sure before trying, I still tried your sample code and I found this in the logs:

2021-10-01 10:16:20 [-][1971][-][error][saml-core] Decryption failed: Algorithm mismatch between input key and key used to encrypt  the symmetric key for the message. Key was: 'http://www.w3.org/2001/04/xmlenc#tripledes-cbc'; message was: 'http://www.w3.org/2001/04/xmlenc#rsa-oaep-mgf1p'

So I would need another hint please ...

**Comment by dsmrt** [comment]
So that error is a little complicated. I probably need to change that error to a warning because it might not actually be an error. The decryption process loops through the different algorithms there until it finds a match, so it might be decrypting properly after that error.

Are you seeing an error after that? Is there an error on the screen?

**Comment by hiasl** [comment]
No, there is no error after that. But in your sample code I do not get into the two foreach loops where you try to debug the attributes of the assertion.

I also took the SAMLResponse when the browser comes back from IDP to the SSO login and base64 decoded it with _samltool.com_. It contains a 
`<saml2:EncryptedAssertion xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion">`
which I can then decode with my key from your plugin again with _samltool.com_. So I know for sure that the assertion is encrypted and in your previous post you wrote, that the code needs to be modified then.

**Comment by dsmrt** [comment]
I have a fix going for this now. I’m going to make it so you’ll have the decrypted assertion at that point. Plus, i might add an easier way to interact with the groups via a new event.

**Comment by hiasl** [comment]
can't await it :-)

**Comment by dsmrt** [comment]
I added a couple things you will be interested in: 
1) I added an event that presents the Craft User Groups that have been: found existing on the user; found from the assertion (that might not help you);  determined to be assigned to the user by the plugin (this will be empty for you but you'll add groups here). This event also has the user element attached to it and the response. I added an example [here](https://saml-sp.flipboxfactory.com/configure/events.html#assign-user-to-a-user-group-based-on-a-property) but this is what it looks like:
```php
Event::on(
    \flipbox\saml\sp\services\login\UserGroups::class,
    \flipbox\saml\sp\services\login\UserGroups::EVENT_BEFORE_USER_GROUP_ASSIGN,
    function(\flipbox\saml\sp\events\UserGroupAssign $event) {
        /** @var \craft\elements\User $user */
        $user=$event->user;
        /** @var \craft\models\UserGroup[] $existingGroups */
        $existingGroups = $event->existingGroups;
        /** @var \craft\models\UserGroup[] $groupsFound */
        $groupsFound = $event->groupsFoundInAssertions;
        /** @var \SAML2\Response $response */
        $response = $event->response;

        // do what you need to do!
        
        // get a list/array of groups (*this is a fictional service and method*)
        /** @var \craft\models\UserGroup[] $groups */
        $groups = $myService->getGroups($user);
        
        // overwrite this property (these will be assigned to the user after event is run)
        $event->groupToBeAssigned = $groups;
    }
);
```

2) I also made it so the Response's assertions are decrypted by the time you get it, so you shouldn't have to decrypt them again.

While testing this I realized that you should have probably gotten an error from that event code I sent you so make sure you have the `config/app.php` configured correctly (this bit me while testing just now). For example:
```php
return [
    'modules' => [
        'my-module' => \modules\Module::class,
    ],
    'bootstrap' => ['my-module'],
];
```

Lastly, I added some docs on group stuff [here](https://saml-sp.flipboxfactory.com/configure/groups.html#user-group-saml-sp-configs) if you want to look it over.

Hope this helps!

**Comment by dsmrt** [comment]
BTW, update to 2.7.1 to see these changes.

**Comment by hiasl** [comment]
OK, first of all, shame on me, you were right, my default module was not bootstrapped, therefore not loaded and therefore I could have never reached the foreach loops ....

BUT: the good news: with your update of automatically getting decrypted assertions, everything is working now. Although of course I have to manually explode the semi-colon separated roles from the response object, it was really easy now.

Thanks for the great support and reaction time!
