### ISSUE TITLE
Update Bindings?

### ISSUE THREAD

**Issue by lindseydiloreto** [flipboxfactory/saml-sp#134]
A technical advisor has requested that I update the "Bindings"... yet I can't seem to figure out how to change those values.

<img src="https://user-images.githubusercontent.com/5309692/135532530-5c73845c-0a7f-4d08-bcf1-fee74310a58e.png" width="440">
 
How can I update these values? They seem to be read-only in every environment.

**Comment by dsmrt** [comment]
:wave: @lindseydiloreto,

They want to change bindings, as in, HTTP POST to HTTP Redirect? Both the ACS and SLO support POST and Redirect. 
 -OR- 
Do they want to change the endpoints like `https://example.com/sso/login`? 

The URL values are pulled from the metadata. This metadata, when changed, needs to be shared with the other entity (the IdP) so they know where to send the Response. And things like the URL should only change when the environment domain/siteUrl changes. If the site url has changed, you might be able to resave that screen and allow the metadata to be rebuilt. Although (depending on the plugin version), you may just have to create a new metadata/My Provider, then verify the site url looks correct. Either way, once that shows how you need, share the metadata with the IdP.

Does that help?

**Comment by lindseydiloreto** [comment]
Hey @dsmrt! 👋 

The second one, the endpoints need to be changed. The parts that I blurred out (`example.com`) are incorrect, and need to be updated.

I'll try re-saving it. And if that doesn't work, I'll chat with our advisor to discuss the next step.

Will let you know how it goes. Thanks!

**Comment by dsmrt** [comment]
Great!

If you are up-to-date with the plugin, there have been some changes with that now being pulled from the site configuration (the selected site on the sidebar of the provider page) instead of the older `siteUrl` general config.

Let me know how that goes!

**Comment by lindseydiloreto** [comment]
Re-saving the provider seemed to do the trick! I believe it properly updated both URLs.

Thanks for the pointers @dsmrt, much appreciated! 🍺
