### ISSUE TITLE
project config migration

### ISSUE THREAD

**Issue by lamboap** [flipboxfactory/saml-sp#137]
hi,

we have 3 environments dev,staging, prod.  We'd only want to apply SSO to the prod instance of CraftCMS.  If we commit and cut a build off staging will that overwrite any fields/settings created on prod for SAML.  I believe it does.  How can we ensure that each environment's SP won't get overwritten/clobbered in the migration?

thanks,
Lambert

**Comment by dsmrt** [comment]
When you are developing new fields on lower level environments they shouldn't affect the existing plugin settings in the project config. Those are separate. If you are making changes to the plugin or plugin settings that is obviously something that will affect production sso/plugin so I'd recommend being able to test with a staging IdP environment.
