### ISSUE TITLE
Enable/Disable a certain IDP via config

### ISSUE THREAD

**Issue by hiasl** [flipboxfactory/saml-sp#148]
Hi,
we have 2 IDPs for CP login, one for the lower 2 staging zones and one for the upper 2. Therefore I would like to show only one of the 2 IDPs at once, depending on the staging zone I am in. Otherwise 2 additional login buttons would appear below the standard CP login button, but only 1 of them would work and could be used.

Is there a way to enable / disable certain IDPs via config?

Thanks,
Matthias

**Comment by dsmrt** [comment]
We don't have anything like that implemented but you can disable them via in the cp. Although, it sounds like that wouldn't be helpful for you.

**Comment by hiasl** [comment]
@dsmrt Enabling/Disabling them would be an option, I could create a console command for that purpose.

Another idea would be to introduce a config option, and use it in samp-sp's LoginController:

```
    /**
     * @return \yii\web\Response
     */
    public function actionIndex()
    {
        $variables = $this->getPlugin()->getEditProvider()->getBaseVariables();

        $condition = ['id'=>2]; // something like that, only take if from config/saml-sp.php
        $variables['providers'] = Saml::getInstance()->getProvider()->findByIdp($condition);
        
        return $this->renderTemplate(
            $this->getLoginTemplate(),
            $variables
        );
    }
```

I could create a PR for that purpose, if you are willing to make it part of your plugin. If yes, do you have any preferences on how to configure it?

Options from my POV:
- id (or array of ids)
- entityId (or array of)
- Or even a DB condition, like what I configured above in the sample code?

And any suggestions on how to name the config option?

**Comment by dsmrt** [comment]
Not too sure about pulling this into the repo. I’m still trying to think this thru and consider with some of the other bigger changes being tossed around. 

If you can get away with the command line updates you mentioned, that’d be great. Really good input!

**Comment by hiasl** [comment]
The command line option worked!
