### ISSUE TITLE
User save failed due to email already taken

### ISSUE THREAD

**Issue by camelskyscraper** [flipboxfactory/saml-sp#149]
Hi,

I am working in an environment where I myself do not have access to any of the SSO accounts to conduct testing on my own. Unfortunately.

We're seeing Internal Server Errors on SSO login (/sso/login/...) with this text:
`User save failed: {"email":["Email \"email@address.com\" has already been taken."]}`
_(email@address.com added as a placeholder for the person's actual address)_

At first we thought this was because someone had manually created a site account with that address — although, why would that be an issue?... it would seem logical (not necessarily simple) that a User account would merge with an SSO login that has the same email address because email addresses are, to my understanding, unique internet-wide.

A possibly-related oddity: out of the four SSO users one of them has their email address as their username, while the other three have apparently Craft-generated strings such as 92978001-3923-41f5-9605-b79f8596388e. Why might that be?

Thanks for any pointers you can give!

**Comment by camelskyscraper** [comment]
Another possibly-related clue: we are assigning SSO Users to User Groups using a "groups" attribute. Is it an issue to manually change a User's User Groups when they might later sign in and not have the same exact groups in their SAML response?

**Comment by dsmrt** [comment]
Yep ... this is a mapping issue where the name id (username from the IdP) is not matching the correctly with the existing user. 

Couple things to look out for:
- If you are using email as the username in craft, override the name id with email. You can do this is in the plugin provider configuration on the IdP. I bet this'll be the fix here.
- Look at the Name Id coming over from the IdP and compare it to the Craft username. Is there any attribute you can over the Name ID with that the IdP is sending, that'll match the Craft's username.

**Comment by camelskyscraper** [comment]
Great, thank you!
I turned off the "use email as username" config setting and that seems to have fixed the issue.

We hit the error because I had manually edited (in Craft) a couple of accounts created through SSO, and when I saved them Craft changed their usernames to their emails. Then the next time they tried to login presumably the plugin tried to create a new User because the username was different(?) and then there was the duplicate email error. Maybe the ability to handle that gracefully is something to iron out in the plugin. You know, in your spare time, haha.

Thanks for the tips!

**Comment by camelskyscraper** [comment]
Furthermore, it looks like I created this issue myself by setting objectidentifier as the Username/NameID Override, not knowing what I was doing. If I had left it as the default this wouldn't have been an issue. And now the usernames are crazy long strings of random numbers and letters. Whoops.

**Comment by camelskyscraper** [comment]
See, I knew I was smart.
Thanks!
