### ISSUE TITLE
XML attribute 'AssertionConsumerServiceURL' in the SAML message must be a URI.

### ISSUE THREAD

**Issue by benjaminkohl** [flipboxfactory/saml-sp#150]
We're not really sure what's going on, but one of our client's Azure SSO integrations stopped working on its own in the last few days. It is a site that hasn't been updated at all since February but I did quickly update the plugin from 2.6.2 to 2.7.3 this morning in hopes that would help but the situation hasn't changed.

Azure is reporting the following issue when anyone attempts to view the site homepage (which should prompt them to log in):

```
XML attribute 'AssertionConsumerServiceURL' in the SAML message must be a URI.
```

I looked at the _Assertion Consumer Service (ACS)_ setting on _My Provider_ in the control panel and it looks like this:

```
$DEFAULT_SITE_URL/sso/login/[UUID]
```

The UUID is the actual UUID. Who/what is responsible for parsing that $DEFAULT_SITE_URL environment variable? I can't see that defined in Craft or in the plugin source. Maybe that is an Azure variable? I've been communicating with our direct contact who is trying to get more info in case something changed with their Azure implementation. Meanwhile, I've been investigating every avenue I can.

In Craft's web.log, I do see some signature validation errors from this morning prior to updating the plugin. It doesn't look like that has occurred since then.

```
2021-12-13 09:31:48 [-][-][f09psllqs0ls638rj5j9pe45qs][error][Exception] Exception: Unable to validate Signature in /home/PATH_TO_SITE/vendor/simplesamlphp/saml2/src/SAML2/Utils.php:195
Stack trace:
#0 /home/PATH_TO_SITE/vendor/simplesamlphp/saml2/src/SAML2/Assertion.php(674): SAML2\Utils::validateSignature()
#1 /home/PATH_TO_SITE/vendor/flipboxfactory/saml-core/src/validators/SignedElement.php(34): SAML2\Assertion->validate()
#2 /home/PATH_TO_SITE/vendor/flipboxfactory/saml-core/src/validators/Assertion.php(107): flipbox\saml\core\validators\SignedElement->validate()
#3 /home/PATH_TO_SITE/vendor/flipboxfactory/saml-core/src/validators/Response.php(94): flipbox\saml\core\validators\Assertion->validate()
#4 /home/PATH_TO_SITE/vendor/flipboxfactory/saml-core/src/validators/Response.php(74): flipbox\saml\core\validators\Response->validateAssertions()
#5 /home/PATH_TO_SITE/vendor/flipboxfactory/saml-sp/src/controllers/LoginController.php(109): flipbox\saml\core\validators\Response->validate()
#6 [internal function]: flipbox\saml\sp\controllers\LoginController->actionIndex()
#7 /home/PATH_TO_SITE/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#8 /home/PATH_TO_SITE/vendor/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams()
#9 /home/PATH_TO_SITE/vendor/craftcms/cms/src/web/Controller.php(190): yii\base\Controller->runAction()
#10 /home/PATH_TO_SITE/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction()
#11 /home/PATH_TO_SITE/vendor/craftcms/cms/src/web/Application.php(274): yii\base\Module->runAction()
#12 /home/PATH_TO_SITE/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction()
#13 /home/PATH_TO_SITE/vendor/craftcms/cms/src/web/Application.php(259): yii\web\Application->handleRequest()
#14 /home/PATH_TO_SITE/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest()
#15 /home/PATH_TO_SITE/public/index.php(28): yii\base\Application->run()
#16 {main}
```

Craft 3.5.19.1
SAML SP 2.7.3
PHP 7.4.26

**Comment by dsmrt** [comment]
:wave: @benjaminkohl ,

This is a new one. `$DEFAULT_SITE_URL` is either set in the `config/general.php`, `config/saml-sp.php`, or at the site level. Can you check a few things?

1. Does the metadata of my provider have `$DEFAULT_SITE_URL` in the raw text. This will not be parsed/rendered. It should show the true URL within that metadata.
2. If 1 is true, resave the my provider and see if it's fixed. 
3. Find where `$DEFAULT_SITE_URL` is set and make sure it's set correctly in the `.env` and within the configurations (`config/general.php`, `config/saml-sp.php`, or on the site within the craft cp)

**Comment by benjaminkohl** [comment]
1. It shows the unparsed version as well. In one spot, I see this:

```
 Location="$DEFAULT_SITE_URL/sso/login/[UUID]"
```

2. After re-saving, it appears the same way.
3. Maybe this is the issue. We don't use .env and instead use an alternate PHP .env.php to set the environment variables and we do not set that particular value. I will try to set that one and see what happens.

**Comment by benjaminkohl** [comment]
The login form now loads as expected but login attempts result in the following 500 error:

```
2021-12-13 16:37:43 [-][-][36phcghrre13ei8vvtgbuqibbg][error][Exception] Exception: Signature required but not found: Response in /home/PATH_TO_SITE/vendor/flipboxfactory/saml-sp/src/validators/SignedElement.php:51
Stack trace:
#0 /home/PATH_TO_SITE/vendor/flipboxfactory/saml-sp/src/validators/Response.php(86): flipbox\saml\sp\validators\SignedElement->validate()
#1 /home/PATH_TO_SITE/vendor/flipboxfactory/saml-sp/src/controllers/LoginController.php(111): flipbox\saml\sp\validators\Response->validate()
#2 [internal function]: flipbox\saml\sp\controllers\LoginController->actionIndex()
#3 /home/PATH_TO_SITE/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#4 /home/PATH_TO_SITE/vendor/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams()
#5 /home/PATH_TO_SITE/vendor/craftcms/cms/src/web/Controller.php(190): yii\base\Controller->runAction()
#6 /home/PATH_TO_SITE/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction()
#7 /home/PATH_TO_SITE/vendor/craftcms/cms/src/web/Application.php(274): yii\base\Module->runAction()
#8 /home/PATH_TO_SITE/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction()
#9 /home/PATH_TO_SITE/vendor/craftcms/cms/src/web/Application.php(259): yii\web\Application->handleRequest()
#10 /home/PATH_TO_SITE/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest()
#11 /home/PATH_TO_SITE/public/index.php(28): yii\base\Application->run()
#12 {main}
2021-12-13 16:37:43 [-][-][36phcghrre13ei8vvtgbuqibbg][info][application] $_GET = [
    'p' => 'sso/login/6ff49084-d799-4831-8c12-290a1351875b'
]
```

**Comment by dsmrt** [comment]
Add this to the saml-sp.php:
```php
return [
    'requireResponseToBeSigned' => false,
];
```

The assertion should be signed. See this issue for more info: https://github.com/flipboxfactory/saml-sp/issues/126

**Comment by benjaminkohl** [comment]
I think we are getting closer to things working again but people on the Azure end are saying the certificate I supplied from the Keychain area of the settings (a long time ago) is expired. I don't remember where that certificate came from. Was that generated by the plugin and is there a way for me to extend its life?

**Comment by dsmrt** [comment]
You can't extend it's life but you can:
1. regenerate a new one
2. resave the provider
3. share the new cert with the AD administers

There's more info here: https://saml-sp.flipboxfactory.com/configure/keychain.html

**Comment by benjaminkohl** [comment]
We generated a new cert and gave it to the IT team that handles the Azure implementation but I am still seeing the "Unable to validate Signature" exception in the logs and nobody can log in. I also set `requireResponseToBeSigned` back to _true_ since that is how it is supposed to be. Are there any other reasons why this exception may have started occurring?

I tried clearing Craft's caches and re-saving the My Provider settings just in case that would help.

**Comment by benjaminkohl** [comment]
When I generated the new cert, did I only need to send them the updated metadata or both the metadata and the cert? Whoever the people are on the other end (there's an unknown number of contacts between us), they aren't very specific about asking for things so I'm just throwing whatever at them.

**Comment by dsmrt** [comment]
sending the new cert is probably enough. Just mane sure to re-save the my provider so everything looks good with the metadata creation. 

Sounds like you are missing their latest cert. Can you have them send you their latest metadata?

**Comment by benjaminkohl** [comment]
This implementation uses the "Metadata By URL" option. Maybe that URL changed? I tried manually removing the metadata to get it to refresh but that didn't help. I've reached out to them to request that URL again in case it has changed.

**Comment by dsmrt** [comment]
I thought you had an implementation with this. 

Can you verify that the metadata at the url (just goto the url and download it maybe) matches the metadata in the metadata field? 

I'm also curious to see if they have a new metadata url.

**Comment by benjaminkohl** [comment]
This is the same Azure SAML implementation that has caused us numerous problems over the years. We have another client with two Okta implementations but those seem to play nicely (knock on wood).

When I paste the URL in my browser, the resulting XML actually looks quite a bit different than what is saved in the "Metadata XML" field in the plugin. I tried overwriting the XML manually and it is getting replaced by the content that was in there before. Does the XML undergo any kind of manipulating after it is fetched via the URL?

**Comment by dsmrt** [comment]
Go into the Azure AD provider in the plugin. Delete the Metadata by URL value. Then paste the value you have from the url that looks different and see if that saves correctly.

There shouldn't be any major manipulation happening but there may be formatting differences. You can prettify the xml like this to compare it easier (I'm on a Mac): 
```bash
curl <metadata-xml-url> | xmllint --format -
```

**Comment by dsmrt** [comment]
Also, feel free to email me and we can get this worked out. 

damien ...at... flipboxdigital.com
