### ISSUE TITLE
Craft randomly times-out when SAML user is logged in

### ISSUE THREAD

**Issue by hiasl** [flipboxfactory/saml-sp#152]
Hey @dsmrt 
We have your SAML plugin running on 3 of 4 staging zones right now successfully (site is not live yet).
We use it login into the CP on a custom CP domain (like described here: https://github.com/flipboxfactory/saml-sp/issues/145)
Users can login, groups are assigned, they can click around a little bit, it looks good ....  and all of a sudden Craft is not responding to this user anymore. You click a link, nothing happens (both normal GET request in CP's main navigation AND ajax requests on other links).

Some other facts:
- This behavior does not happen with "real" Craft users (not SAML created/logged in). Craft is performing great, no delays at all. They can continue to use the CP even while the other SAML user's request is waiting for its timeout.
- Everytime a user logs in via SAML, I get this error in my log:
`Decryption failed: Algorithm mismatch between input key and key used to encrypt  the symmetric key for the message. Key was: 'http://www.w3.org/2001/04/xmlenc#aes256-cbc'; message was: 'http://www.w3.org/2001/04/xmlenc#rsa-oaep-mgf1p'`
In a previous issue you state to ignore this error, I just want to mention it (https://github.com/flipboxfactory/saml-sp/issues/78#issuecomment-680089522)
- The customers setup is quite complex, lot of firewall stuff. 
 
My thought: Does the plugin from time to time (random) do server to server requests to the IDP to re-validate the users SAML session? 
If yes, could it be a networking issue that Craft / your plugin is waiting for a response from the IDP which it does not get due to firewall restrictions and therefor the browser requests time out?

If you have any hint that could bring me in the right direction, I would be very thankful!
cheers,
M.

**Comment by dsmrt** [comment]
:wave: @hiasl ,

First off, the decryption failure error probably needs to be reclassified as a warning. Added a issue here: https://github.com/flipboxfactory/saml-sp/issues/153

The performance degradation shouldn't have anything to do with the plugin unless it's during the time of sso login/logout. This will be happening when the url is on one of the sso based url segments -- when the SAML actions are being processed. The plugin never reaches back out to the IdP unless Craft's user session has expired and it trying to reinitiate login. Which would work just like normal Craft session expiration, then redirect to the plugin sso request endpoint to reach back out to the IdP.

Couple things I'm thinking you can check:
- Are there large user properties synced from the IdP consuming memory (maybe injected into the page for JS access?) that aren't there with native Craft users?
- Is the SSO logout button a memory hog? Sounds crazy but might be worth looking at.

**Comment by hiasl** [comment]
What do you mean with "is your sso logout button a memory hog"? How can a button be a memoryhog. thanks!

**Comment by dsmrt** [comment]
I’m just trying to figure out how the plugin can affect page timeout. If there is a process that builds the logout button (sso logout specifically) this could be something you’d want to try to disable and see if it makes a difference. 

Again, i don’t think this is the case but there’s only a couple of things i can think of that’d cause what you’re describing.
