### ISSUE TITLE
Authenticating Front End User

### ISSUE THREAD

**Issue by masonry47** [flipboxfactory/saml-sp#160]
Hey @dsmrt 

We are having a new issue (likely a config thing) on authenticating front end users. In the past we have successfully authenticated Craft control panel users with Azure and Okta.  But in this case we are trying to wrap our heads around the configuration for front end users from a different IDP.    So far we have successfully exchanged meta data and did get a login path and logout path from the meta data, but are getting 

"Service Provider is not found. Possibly a configuration problem. My Provider/Current EntityId: https://domain-here"

Thanks in advance for an ideas!

**Comment by dsmrt** [comment]
:wave: @masonry47,

Can you go to the Plugin provider list and see if "https://domain-here" (or what ever it is) you can find it in the list of IPs. Make sure to do this on the server/craft environment that is giving you the error. There should be text next to it (in the table row) that says  `(My Provider)`.

**Comment by masonry47** [comment]
Thanks!

In the Service Provider List we do a have a row where the entity ID does match the domain in the error message. Though the entity ID does have a trailing slash and the other error output does not.

**Comment by dsmrt** [comment]
Ok cool. It has to be an exact match. That value can be a uuid or some other random string, it just is more common to have it based on a url/uri.

Add the trailing slash in the provider edit screen and that should fix the issue. Let me know how it goes.

**Comment by masonry47** [comment]
That got it!  Thank so much

**Comment by darylknight** [comment]
Came here with the same issue - I told the client to set it up as `https://staging.ourwebsite.com`, and they used `https://staging.ourwebsite.com/` 🤦 
Adding the trailing slash at our end fixed it.
