### ISSUE TITLE
Multiple IDP Providers

### ISSUE THREAD

**Issue by masonry47** [flipboxfactory/saml-sp#162]
Hey @dsmrt 

Really more of a question here.  We are integrating with 2 IDPs.  One for front end users and one for Craft authors.  The question here is do we need to provide a unique service provider per IDP.  Or can we use the same Service Provider for both IDPs we have setup.  Thanks in advance!

**Comment by dsmrt** [comment]
:wave: @masonry47,

Yep! you can use the same SP for multiple IdPs. [Here's some info in the docs](https://saml-sp.flipboxfactory.com/configure/login.html#explicit-config-recommended).

Hope this helps!

**Comment by masonry47** [comment]
@dsmrt Thanks!

I think to clarify, we would need two different login paths in the same environment. The docs here show how to set different paths for different environments.   Thanks again!

**Comment by dsmrt** [comment]
By default the admin cp login will show all of the IdPs available. You could label these in a way so they stand out for the Craft authors. Then for the loginPath, use the frontend user IdP (which aligns with the purpose of that config). 

If further biz logic is needed ....
Those docs show that you can specify the loginPath with the specify IdP you want the users to login into: `/sso/login/request/<IdP provider uid>` (furthermore, you can specify the IdP and the SP as shown at the bottom of the page in those docs).

Although I'm not a fan of getting to complicated here, you can use biz logic (like uri or an env var) in that config file to present the correct IdP path for loginPath.

Does that help?
