### ISSUE TITLE
Support for Craft 4

### ISSUE THREAD

**Issue by timeverts** [flipboxfactory/saml-sp#169]
Hi @dsmrt,

We have several Craft 3 sites using your plugin and are really keen to upgrade them to Craft 4.

Could you please add support for Craft 4 (see https://craftcms.com/docs/4.x/extend/updating-plugins.html)?

Thanks.

**Comment by dsmrt** [comment]
👋 @timeverts,

We have just started this and gauging the effort. I’m hoping it isn’t too bad and we can get something out soon.

**Comment by dsmrt** [comment]
Quick update. I’m pretty close to releasing this update. Just testing a few edge cases. I’m planning on EOW, this week.

**Comment by dsmrt** [comment]
Update the plugin to [4.0.0](https://packagist.org/packages/flipboxfactory/saml-sp#4.0.0) 🥳

**Comment by darylknight** [comment]
I'm still seeing "UNKNOWN" for the sub-plugin(?) that comes with this, "KeyChain". Is this also ready to go?

![image](https://user-images.githubusercontent.com/1250017/185611136-9ea676c9-79bb-4554-b6f3-58e7f40a7b6d.png)

**Comment by dsmrt** [comment]
Hi @darylknight 👋 

Where are you seeing that? Is that within Craft?

KeyChain is a dependency and is compatible with Craft 4. https://github.com/flipboxfactory/keychain

We never released it in the plugin store but because we really only use it in the SAML plugins (there was thoughts of using it in other places). That might be the reason.

**Comment by darylknight** [comment]
This is in Craft 3 under admin/utilities/upgrade, to see which plugins are ready for Craft 4. I've always found it kind of weird that it installs itself along with the SSO plugin, unlike any others that I've used.

**Comment by dsmrt** [comment]
ok. I’m assuming sprout base and nystudio’s base plugin package is a dependency but not a plugin. Keychain is a plugin. It has it’s own db operations on install, etc. Composer type is craft plugin. You can install it and use it on it’s own as a plugin. Our saml-core is basically like the sprout base etc. Its just a normal composer package dependency.

**Comment by darylknight** [comment]
Got it, thanks for confirming :) If it is a real plugin, you may want to mark it as Craft 4 ready, whatever the process is for that.
