### ISSUE TITLE
"Email cannot be blank" on login/creation for a user whose claims are set correctly in the AD

### ISSUE THREAD

**Issue by maurocolella** [flipboxfactory/saml-sp#170]
Hi,

This is happening when using the plugin with Azure AD. We have two separate configurations, a test Azure App with Outlook/Live as the IdP, and a real configuration with an enterprise AD (still Azure) as the IdP.

On the former, the name and emailaddress claims are set automatically; the name claim is of the form 

`username_hotmail.com#EXT#@usernamehotmail.onmicrosoft.com`

While the emailaddress claim is simply the email address.

On the latter, the name and emailaddress claims are both email addresses, though not exactly identical (alias).

For no reason that I can comprehend, given that a lot of the respective configs are identical, we get this `"Email cannot be blank"` when attempting to login with the latter config.

**Comment by dsmrt** [comment]
:wave: @maurocolella,

The IdP that's creating the erroring (enterprise AD) is missing a config in the mapping for email address (`emailaddress` I believe you said). Add `emailaddress` to the Configure > Mapping area for the IdP Provider in the plugin backend (again, enterprise AD).

The attribute mapping area looks like this but your values from the IdP will look different (`Email` vs `emailaddress`):
![craft-mapping-attributes e22e3461](https://user-images.githubusercontent.com/1995478/168913098-507f69f1-19c6-468a-9d79-05c7aa0d8e8c.png)

**Comment by maurocolella** [comment]
The mappings are correct. In fact, we tried with/without explicit mappings, and we gathered and compared requests and responses from the AD where the email isn't retrieved, and the one where things work. They are 95% identical, and all of the standard claims are definitely configured identically.

We are now looking at additional measures to get to the root cause of this.

Could some other factor be causing the loss of data? Something to do with encryption? Some specific headers? 

I appreciate keeping this issue open while we get to the bottom of it.

**Comment by dsmrt** [comment]
If you can turn on dev mode, look at the logs. It seems like the attribute mapping is off (email is not found). I’ve seen this error tens of times it’s always the mapping is off. 

When dev mode is on you’ll see a lot of helpful output including the response xml and attribute mapping debug.

**Comment by maurocolella** [comment]
We have the response xml. The attribute mapping is exactly the same as on
the sp where things work.

Thanks for the pointers, I'll keep you posted.

**Comment by dsmrt** [comment]
The attribute mapping might be the same but the its seems like the the attributes coming through Response xml is not. Are you sure the attributes being sent match the mapping set? It seems like the IdP that is working has a different attribute name than the other (ie, email vs EmailAddress, or something along those lines).

The logs will help debug this. Here's a tail command I use to filter the saml logs.
```sh 
tail -f storage/logs/web.log | grep -A 10 '\[saml-'
```

Also, tools like this might help: https://chrome.google.com/webstore/detail/saml-devtools-extension/jndllhgbinhiiddokbeoeepbppdnhhio

Also, if you want, you can contact me here and we can exchange more sensitive data like Response: https://www.flipboxdigital.com/contact/

**Comment by maurocolella** [comment]
I'd be happy to, but as a 3x certified AWS associate, Oracle and Linux
Foundation certified dev, and independent contributor to research for
Columbia University and EPFL, pardon me for pointing out that I do not need
training wheels.

No offense meant. I appreciate the availability: yes, the claims in the
response.xml are identical. We have a remote session scheduled Friday to
find out exactly what could differ, but it's far from obvious from the
response content.

I will keep you posted. I do appreciate and hear your feedback, and I would
prefer if it were a configuration matter.

**Comment by maurocolella** [comment]
So, some feedback @dsmrt .

We've had that session. The client/partner have deleted their Azure AD app, re-created it.

I am going to have to assume some issue with the AD app itself.

However, right now, we're seeing this error instead:
https://stackoverflow.com/questions/31574596/simplesamlphp-unable-to-validate-signature-error

"Unable to validate signature".

Our CMS is set not to require signatures on assertions and responses.

We get the metadata using the federation metadata url.

We tried clearing the URL, and importing the metadata manually.

We tried recreating the app once more, updating the metadata URL. I was able to verify that inline certificates (in the metadata) were up-to-date, but the error was exactly the same. "Unable to validate signature".

By default, Azure assigns a certificate to SAML encryption, which we tried to configure to sign assertions, and assertions + responses, but I am not sure how to integrate that certificate - or if I need to integrate it - within our own CMS and plugin setup.

That's where we are right now.

Please advise.

**Comment by dsmrt** [comment]
`Unable to validate Signature`... means you need to update the metadata with the IdP's latest KeyDescriptor certificate value on the Craft side. That has the public key in it which the plugin uses to verify the signature. 

This video tutorial may be helpful: https://saml-sp.flipboxfactory.com/idps/azure-ad.html

**Comment by maurocolella** [comment]
@dsmrt how would I achieve that? By resaving the settings for the iDp with the relevant federation metadata url?

**Comment by dsmrt** [comment]
Get the metadata from Azure and resave it in Craft. The metadata has the cert in it.

**Comment by maurocolella** [comment]
Yeah. We did that. No dice. Will give it a shot again next week. Thanks.

**Comment by billymedia** [comment]
This might have absolutely nothing to do with your issue, but i had the same problem, everything looked fine in AD but i would get the Email error on login. Turned out, i had another disabled Idp, and the login process was picking up the mappings from the disabled idp which were different to the active idp i wanted to use, once i  deleted the mappings in the disabled idp, everything started working.

**Comment by maurocolella** [comment]
Appreciate the concern. I am not usually superstitious when it comes to
software, but there appears to be non-obvious factors involved.

I'll continue digging.

**Comment by maurocolella** [comment]
So, @dsmrt , thanks for the pointers. I have once more (3x) verified today that the KeyDescriptor's X509 certificate is identical within the CMS, through the federation metadata URL, and also via manual export.

It's the same. To the last bit.

Yet, as of today, our client/partner is still encountering the same issue/same error with: 
`Unable to validate Signature`

I am thinking that something in their metadata and/or assertions throws parsing off somehow, resulting in some fields being misreported as empty or invalid.

Happy to provide any information needed to resolve this.

**Comment by dsmrt** [comment]
You may have to verify that the craft plugin on that environment is pointing to the correct Azure Ad app. Is the loginPath in the `config/general.php` pointing to the correct IdP config/provider in the provider list? Have you checked the debug logging and seen the response? Is the issuer in the response the correct issuer/entity id?

The logging will also show attempts to verify the signature with all of the supported algorithms. That might be helpful as well. 

I assume something is misconfigured and things just need to be synced up. This is a fairly common issue and it’s just the IdP metadata is out of sync.

**Comment by maurocolella** [comment]
Hi.

> Is the loginPath in the config/general.php pointing to the correct IdP config/provider in the provider list

We've set the login url explicitly within the Azure AD environment, for testing. It does point to the correct IdP.

> Have you checked the debug logging and seen the response.

Yes. We capture the request and response xml using the Azure testing environment (+ Chrome plugin). The issuer/entity id in the response is correct.

Regarding logs: we are using AWS on an Elastic Container Infrastructure. This means that logs are rendered available through Cloudwatch.

What I am looking for? Any specifics about the error message(s)? 

I can guarantee that the metadata in our database is current, and matches the metadata posted by Azure. As mentioned, we have verified this multiple times, using multiple approaches.

Also, the containers are based on fairly standard php images, hence I believe that the set of supported algorithms should meet the requirements.

Thanks for any pointers about investigating potential issues during signature checks.

**Comment by dsmrt** [comment]
> What I am looking for? Any specifics about the error message(s)?

I'd look at anything matching `[saml-*]`, like `[saml-sp]` or `[saml-core]`. These are log points that the plugin and libraries add when in `devMode=true`. There may be something in the logs there that show what the misconfiguration is (especially with the email address error).

One last thing to disable any providers that are not being used. If the metadata is up-to-date, that might show where things are going wrong with the misconfiguration.

Beyond that I'm not sure what else I can do to help you with this issue. Implementation is outside builtin plugin support.  Metadata seems out of sync or the providers aren't matched up right. This is a common issue when someone is having problems implementing the plugin and SAML in general. The code isn't finding the right cert to verify the signature (because it's not there).

Here are some options I can see you going down: 

1. Scrap this environment for now and get the plugin working on your local. Follow the video I posted above (here: https://saml-sp.flipboxfactory.com/idps/azure-ad.html), get it working locally, then replicate that on the environment with the issue.
2. Hire us to help implement/consult and get it up and running. I'd be happy to help get this wrapped up.

If you do have any sensitive data that you'd like to share with me, again, reach our via the contact form on our website. https://www.flipboxdigital.com/contact/

**Comment by dsmrt** [comment]
Also, I don't know if this helps but look at some of the closed issues with "unable to validate" https://github.com/flipboxfactory/saml-sp/issues?q=is%3Aissue+is%3Aclosed+%22Unable+to+validate%22

A lot of them are using Azure AD

**Comment by dsmrt** [comment]
Closing but let me know if you need anything else.
