### ISSUE TITLE
Entity ID of SP not used

### ISSUE THREAD

**Issue by FrankZwiers** [flipboxfactory/saml-sp#171]
We have a setup with multiple IDP's that require different Identity IDs(e.g. different Azure tenants and different Azure applications for different environments). When attempting to authenticate via the `/sso/login/request/<IdP provider uid>/<SP provider uid>` structure it does not send the Entity ID of the SP but always the default Entity ID.

This could be solved by changing line 91 of src/services/messages/AuthnRequest.php to
`$serviceProvider->getEntityId()`

**Comment by dsmrt** [comment]
👋 @FrankZwiers ,

Good catch. I think you have this right. I’m going to review and get a patch out.

**Comment by dsmrt** [comment]
Hi @FrankZwiers,

Great catch and good issue. 

Give 2.7.4 a try: https://packagist.org/packages/flipboxfactory/saml-sp#2.7.4

Thanks!

**Comment by FrankZwiers** [comment]
Works like a charm, thanks for the quick support.
