### ISSUE TITLE
Google - Signature required but not found: Response

### ISSUE THREAD

**Issue by bromtec** [flipboxfactory/saml-sp#173]
![Screen Shot 2022-07-03 at 12 40 49 PM](https://user-images.githubusercontent.com/5491531/177054980-39629f59-b51c-40be-ac31-ef14b730ed7f.png)

Have followed documentation as close as possible, trying different options in Google Suite, but continue to get this error.  

Any ideas or documentation specific to setting this up with Google Suite / Workspace ?

**Comment by dsmrt** [comment]
👋 @bromtec !

sorry for the late response! 

I just added some instructions for this here:  https://saml-sp.flipboxfactory.com/quick-start.html#other-plugin-configurations-and-recommendations

Add the config for `requireResponseToBeSigned` To false as specified there in the saml-sp.php

**Comment by dsmrt** [comment]
Closing. Let me know if you still need help.
