### ISSUE TITLE
UnparseableXmlException: Unable to parse XML

### ISSUE THREAD

**Issue by okkimus** [flipboxfactory/saml-sp#178]
Hello!

I'm trying to get SAML working for a Craft website. After going back and forth with IT-department, I finally managed to get the configuration file, and added it as identity provided in the plugin. The error comes after the login, and "Internal server error" is showed by Craft.

After setting the configuration to our part, I got the following error:
`[saml-core] Signature required but not found: Response`
I found [this](https://github.com/flipboxfactory/saml-sp/issues/147#issuecomment-979695938) and went ahead and set the following setting:
`'requireResponseToBeSigned' => false,`

But now I'm getting other error. First a bunch of `Decryption failed` but these should be just warnings according to earlier issues. However the log now has this error:
```
2022-10-10 14:28:35 [-][-][-][error][Exception] SAML2\Exception\UnparseableXmlException: Unable to parse XML - "FATAL[74]": "EndTag: '</' not found
" in "(string)" at line 4 on column 45" in /<route to my instace>/vendor/simplesamlphp/saml2/src/SAML2/DOMDocumentFactory.php:58
Stack trace:
#0 /<route to my instace>/vendor/simplesamlphp/saml2/src/SAML2/Utils.php(504): SAML2\DOMDocumentFactory::fromString()
#1 /<route to my instace>/vendor/simplesamlphp/saml2/src/SAML2/Utils.php(531): SAML2\Utils::doDecryptElement()
#2 /<route to my instace>/vendor/simplesamlphp/saml2/src/SAML2/EncryptedAssertion.php(122): SAML2\Utils::decryptElement()
#3 /<route to my instace>/vendor/flipboxfactory/saml-core/src/helpers/SecurityHelper.php(146): SAML2\EncryptedAssertion->getAssertion()
#4 /<route to my instace>/vendor/flipboxfactory/saml-sp/src/validators/Assertion.php(95): flipbox\saml\core\helpers\SecurityHelper::decryptAssertion()
#5 /<route to my instace>/vendor/flipboxfactory/saml-sp/src/validators/Response.php(110): flipbox\saml\sp\validators\Assertion->validate()
#6 /<route to my instace>/vendor/flipboxfactory/saml-sp/src/validators/Response.php(89): flipbox\saml\sp\validators\Response->validateAssertions()
```

I tried to set the other security settings to false discussed [here](https://saml-sp.flipboxfactory.com/faqs.html#signature-required-but-not-found), but that didn't help either.

I haven't implemented SAML before, so I'm bit out of ideas. Any tips that could help me forwards?

Plugin version: 2.7.4
CraftCMS version: 3.7.46 (Pro)

Edit: Formatting.
Edit2: Added versions.

**Comment by okkimus** [comment]
Hey Damian, thanks for fast reply!

I tried to lint the xml files, and they all were fine.
- metadata.xml (identity provider) I got from the IT department
- metadata I sent them (service provider)
- I also decoded the base64 string I managed to catch with developer tools that was sent to my Craft site...but after decoding and linting that was fine as well 🤔 

I think the authentication is successful on Azure side:
```xml
<samlp:Status>
    <samlp:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Success"/>
</samlp:Status>
```
I'm starting to think that there's something wrong in the payload that is encrypted. Any tips how I could decrypt it?
```xml
<e:EncryptionMethod Algorithm="http://www.w3.org/2001/04/xmlenc#rsa-oaep-mgf1p">
    <DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>
</e:EncryptionMethod>
```
Key is issued by keychain@flipboxdigital.com, so I'd say this is using the key generated by the plugin.
And then I have in the KeyInfo-block:
```xml
<e:CipherData>
    <e:CipherValue>ENCRYPTED PAYLOAD</e:CipherValue>
</e:CipherData>
```
And separate <xenc:CipherData>-block with <xenc:CipherValue> and the payload.

**Comment by dsmrt** [comment]
Sorry i was confused at when the error was happening. I thought it was happening on metadata save. 

Are there any attributes that are being passed that could have html or xml in them. Are you able to turn off encryption briefly to test without it?

**Comment by okkimus** [comment]
No worries!

I guess it could be possible that some of the attributes have html or xml in them. It just occurred to me that it might have something to do with testing account we were provided.

The problem is, I don't have access to the Azure AD since that's behind a clients' IT department. And the whole implementation have been dragging over several months whilst we have been trying to get in contact with someone who can reply us.

However, I guess we might need to go through the IT department again. I appreciate all the help! ❤️

**Comment by dsmrt** [comment]
This definitely a new one for me. Very strange. 


It might even be worth diving into the code, at the exception and seeing if you can print the string after it’s decrypted and before it’s loaded as xml, but that might not be straightforward. 

Let me know if you find out more.
