### ISSUE TITLE
4.0.3 isn't installing correctly

### ISSUE THREAD

**Issue by darylknight** [flipboxfactory/saml-sp#179]
- Change composer.json to `"flipboxfactory/saml-sp": "4.0.3",`
- Run `composer update`

Output:
```
❯ composer update
...
- Upgrading flipboxfactory/saml-sp (4.0.2 => 4.0.3): Extracting archive
...
```

- 4.0.3 is still showing as an available update
- Run `composer update` again

```
❯ composer update
Loading composer repositories with package information
Updating dependencies
Nothing to modify in lock file
Installing dependencies from lock file (including require-dev)
Nothing to install, update or remove
```

Utilities > Plugins is still showing that 4.0.2 is installed.

**Comment by dsmrt** [comment]
You are correct. Thats for pointing this out. The composer version is correct though. I’ll update this later but you can use `composer show` to verify which version is installed: https://getcomposer.org/doc/03-cli.md#show-info

**Comment by aelvan** [comment]
Would be great with a fix for this, that update notification is giving my OCD hell.

**Comment by dsmrt** [comment]
🤣 sorry to put you through that @aelvan 

You earned the update. Upgrade to 4.0.4 and all should be ok.

**Comment by aelvan** [comment]
I CAN FINALLY BREATH AGAIN!

Thanks! 😜
