### ISSUE TITLE
Formatting issues in the side panels

### ISSUE THREAD

**Issue by uandco** [flipboxfactory/saml-sp#182]
The side panels lack padding:

<img width="372" alt="image" src="https://user-images.githubusercontent.com/26996169/204938975-7348f329-d8ab-422f-a141-d99c7b00b652.png">

<img width="376" alt="image" src="https://user-images.githubusercontent.com/26996169/204939098-46c76e56-d8f9-4b54-a76d-52ff09898deb.png">

Looks like a regression with Craft 4

Version info:
Craft edition & version | Craft Pro 4.3.4
SAML Service Provider | 4.0.4

**Comment by dsmrt** [comment]
Updated with new versions in core and sp package. Update using this cli command: `composer update flipboxfactory/saml-core flipboxfactory/saml-sp`

**Comment by uandco** [comment]
Hi, thanks for fixing this, but the code seems unnecessary complicated.
You're fighting what Craft provides out of the box with inline styles, which are prone to causing issues with Craft upgrades or custom control panel styles.

For example cleaning up the code the "site" block achieves the same without the extra inline styles:

<img width="606" alt="image" src="https://user-images.githubusercontent.com/26996169/212604001-41e0e486-82ee-4a89-9c1a-05b66fc07be1.png">

(it's still missing a `for` attribute on the label though). The same kind of markup simplification can be applied to the entityID field (see for example how Craft does it out of the box for the "slug" field in entries)
