### ISSUE TITLE
Bindings for both SP and IDP contain NEED_TO_CHANGE

### ISSUE THREAD

**Issue by vdesroches-newtrax** [flipboxfactory/saml-sp#193]
I used the following video to configure the SAML plugin: https://www.youtube.com/watch?v=Y1rau_dkdAU

For some reason, the bindings (for SP) and login/logout paths (for IDP) show "NEED_TO_CHANGE" in place of what should be "sso" (see the images below).

![image](https://github.com/flipboxfactory/saml-sp/assets/139374994/67c18d8d-1790-4521-87fd-589ad50fb6fe)

![image](https://github.com/flipboxfactory/saml-sp/assets/139374994/6650cb85-5a4a-492a-8a88-73fd5323cb9d)

At first, I thought it was an issue with the Entity ID within the SP configuration because by default it's named "NEED_TO_CHANGE", but it doesn't appear to be.

What I tried so far:
- Re-saved the existing SP
- Changed the Entity ID
- Created a new SP and changing Entity ID
- Created a new SP with default Entity ID, edit then save

**Comment by dsmrt** [comment]
It seems like someone might have updated the plugin settings. This can also be a config in `config/saml-sp.php`, under `endpointPrefix` (see the config in the core lib [here](https://github.com/flipboxfactory/saml-core/blob/93b6ae4df563868cde9ec7b10192697f148f4d5a/src/models/AbstractSettings.php#L34)). Can you goto the plugin nav on the side bar in the craft admin, then look at the settings there? If not, the the `config/saml-sp.php`.

Someone must have put NEED_TO_CHANGE in one of those places. Change it back to what you need (`sso` or what ever), then you need to resave your craft's site metadata.

**Comment by NewtraxTeamIT** [comment]
That was it! I went into the Craft CMS Settings, then Plugins and updated the endpointPrefix variable to "sso".

All I had to do afterwards was re-create the Service Provider in Craft, as it still showed NEED_TO_CHANGE in the ACS and Logout URLs, and update Azure with the new URLs.

It's working like a charm now. Thanks for your help!

**Comment by vdesroches-newtrax** [comment]
That was it! I went into the Craft CMS Settings, then Plugins and updated the endpointPrefix variable to "sso".

All I had to do afterwards was re-create the Service Provider in Craft, as it still showed NEED_TO_CHANGE in the ACS and Logout URLs, and update Azure with the new URLs.

It's working like a charm now. Thanks for your help!
