### ISSUE TITLE
I am trying to use OKTA for the control panel only (and have it be the only option to login), while using another provider for the front end

### ISSUE THREAD

**Issue by J-Protz** [flipboxfactory/saml-sp#194]
Is this possible via this plugin? We are already using a provider on the front end, and now the client wants to use OKTA to sign in to the CP. I looked through the docs but am honestly pretty new to this and could use some help.

OKTA is being used for security, so I want to remove the option to login via normal means entirely. This also needs to not affect the front end. 

I did look through the docs and previous issues but didn't see anything that was quite what I was looking for.

**Comment by dsmrt** [comment]
Yes! This is considered IdP initiated login. Okta will have an app for craft (after you configure it). Then you can click the button and it’ll login the user in.

**Comment by dsmrt** [comment]
@J-Protz Let me know if you need any more help here. Closing for now.

**Comment by J-Protz** [comment]
Hey there @dsmrt , I am finally trying to integrate this. 

I have configured it to what I thought was correct, when I get to the admin, I click the button and it brings me to okta. I sign in, and it brings me back to the CP, however it's not logging me in.  I am pretty new to SSO so I am having trouble debugging this, not seeing much in the network tab

The other thing is we will need to somehow completely disable the normal login button(s) and form from appearing, as this would defeat the security measure in place. Could you help point me in the right direction please?

One thing I am unsure of, is the okta account I am using doesn't currently have a matching admin user in craft, could this potentially be the problem? I would expect an unauthorized error instead.

**Comment by dsmrt** [comment]
If you got back to the CP and are seeing a 403 make sure

**Comment by J-Protz** [comment]
I do not see a 403, and the okta login does not seem to be creating a user at all. I tried to tie in to the saml events and log some data and I am just seeing nothing. I'm unsure if something was set up wrong on my side or OKTA. Meeting with the guy who set up the okta app today to double check it matches the documentation provided.

**Comment by dsmrt** [comment]
What are you seeing when you get back to the CP? Please be careful not to share sensitive info.

**Comment by J-Protz** [comment]
Sorry I dont know how I missed this reply until today - but I'm simply seeing nothing, just the login page. I have confirmed to the best of my ability that the okta side was set up correct. we had missed the certificate upload originally, but fixed this. It simply brings me back to the admin, and nothing happens. As if it's the first time loading the page.

I do have screenshots of the okta set up so I can confirm any questions, and obviously have access to my own admin set up. I am unsure as to what would be safe to share (this is just for local, so I assume most of it), but don't want to just dump all the screenshots here lol.

For reference however, we do have 2 providers being used. One is via front end, and the other is just for the CP.  This is partially why I wonder if maybe I have set something up wrong. Especially when setting up the CP as it's own site, it didn't quite look exactly as it did in the docs.
![cp-site](https://github.com/flipboxfactory/saml-sp/assets/70289763/0dfc8863-b2cf-4352-9571-6fa474c98485)

**Comment by dsmrt** [comment]
Can you copy and paste the single sign on url for the app configured in Okta? You can disguise the host. This should point to the assertion consumer service url on the craft side.

**Comment by dsmrt** [comment]
Also, just to be sure you haven’t missed this, here is info on how to configure Okta: https://saml-sp.flipboxfactory.com/idps/okta.html#okta

**Comment by J-Protz** [comment]
I did use that link, but thank you! 

Here is the SSO on okta's side. ~/admin/sso/login/786a1fcb-8c5c-
4fc3-886e-17d2339bb478 

I am not familiar with what the assertion consumer service url is referring to, sorry very new to this.

**Comment by dsmrt** [comment]
Edit that sign on config by removing `admin` in the url. Having admin in there is forcing login, and ignoring the incoming message. 
Assertion consumer service url is where Okta will post the identity and auth info.

**Comment by J-Protz** [comment]
Okay - however my Assertion consumer service url in the control panel is  ~/admin/sso/login/786a1fcb-8c5c-4fc3-886e-17d2339bb478 - how do I change this to remove the admin part? It is grayed out.

**Comment by J-Protz** [comment]
I changed the entity ID to <my-website>/admin, is that potentially the problem here? I wanted it to point to the control panel. We already had a provider for the front end that pointed to `services.<my-website>/`, which is where the front end uses SSO, so I figured this should point to the CP.

**Comment by dsmrt** [comment]
What plugin version number are you using?

You can simply remove `admin` from the Sign-On input field in Okta. It doesn't need to change on the plugin side.

The Entity ID can be whatever you want. It's the unique id for your craft instance.

**Comment by J-Protz** [comment]
I am using 2.7.5.

I made a new provider to test out where the Assertion consumer service url was being generated from - it looks like it's based off the site url I choose. I am having this provider point to the control panel site I set up, which points to  `<my-site>/admin` . This seems to follow what was in the documentation for the plugin seen here https://saml-sp.flipboxfactory.com/examples/multi-site-with-cp-login.html#solution

Do I need to change this so that the Assertion consumer service url does not have `/admin`?

**Comment by dsmrt** [comment]
I believe `admin` in the urls is fixed in later iterations of the plugin so you may want to look at upgrading. Not urgent but just know that it might fix some of the things you are seeing. 

It's better to use the non-admin url for some of those `/sso` actions. You don't need to change anything on the craft side, just edit the url input on the Sign-on in Okta.

**Comment by J-Protz** [comment]
later versions must be for craft 4+, we're still on 3.9 with no available updates. I'll try that out and see how it goes, thank you.

**Comment by J-Protz** [comment]
I got this error when updating just the SSO login from okta.

```Errors during validation: Destination in response "<my-site>/sso/login/786a1fcb-8c5c-4fc3-886e-17d2339bb478" does not match the expected destination "<my-site>/admin/sso/login/786a1fcb-8c5c-4fc3-886e-17d2339bb478"Recipient in SubjectConfirmationData ("<my-site>/sso/login/786a1fcb-8c5c-4fc3-886e-17d2339bb478") does not match the current destination ("<my-site>/admin/sso/login/786a1fcb-8c5c-4fc3-886e-17d2339bb478")```

**Comment by dsmrt** [comment]
Ok ... I just realized we need to change the `@web/admin/` to just be the `@web` or to simply exclude the admin in the endpoints. Then, resave the service provider attached to that site in the SAML plugin. then the urls should match.

**Comment by J-Protz** [comment]
Okay - will this still separate the CP as it's own site though? I need to keep this separate from the front end, as the front end uses a different provider.

**Comment by J-Protz** [comment]
Okay - will this still separate the CP as it's own site though? I need to
keep this separate from the front end, as the front end uses a different
provider.

**Comment by J-Protz** [comment]
This did work - just not sure how this may effect separating front end form admin.

**Comment by dsmrt** [comment]
Is the hostname on the front end the same as the cp? If so, you can use the same craft site for both. From the plugin’s perspective, it only needs the site attachment for access to the base url.

**Comment by dsmrt** [comment]
Going to close this for now. Let me know if you have any other questions.
