### ISSUE TITLE
Redirect on saml login 

### ISSUE THREAD

**Issue by WITwebmaster** [flipboxfactory/saml-sp#198]
Hi 
Hope you could give me some guidance on how to redirect on saml login. I am using the user directory as a staff profile facility with custom fields, and I want to redirect users to /admin/myaccount?site=default on login. 
I tried this in my saml.sp.php config but it didn't work 
```
// Inside /config/saml-sp.php
use flipbox\saml\sp\controllers\LoginController;
use flipbox\saml\sp\events\RelayState;
use yii\base\Event;

return [
    // Other SAML SP configuration settings...

    // Event handling configuration
    'on beforeRelayStateRedirect' => function ($event) {
        Event::on(
            LoginController::class,
            LoginController::EVENT_BEFORE_RELAYSTATE_REDIRECT,
            function (RelayState $event) {
                // Modify the redirect URL
                $event->redirect = $event->redirect. '/admin/myaccount?site=default&logged-in-via=sso';

                // Log information for debugging or tracking
                \flipbox\saml\sp\Saml::info('Raw RelayState: ' . $event->relayState);
                \flipbox\saml\sp\Saml::info('User will be redirected to: ' . $event->redirect);

                // Other information related to the SSO event
                \flipbox\saml\sp\Saml::info('IdP: ' . $event->idp->getEntityId());
                \flipbox\saml\sp\Saml::info('SP: ' . $event->sp->getEntityId());
            }
        );
    },
];

```
Any help is very appreciated

**Comment by WITwebmaster** [comment]
Hi 
Thanks for such a comprehensive answer. I think adding the relay state is the best way to go and I have talked to out IT dept about it . They have done relaynstate before on other azure saml setups, but they have always used a simple URL .They want to know is there any reason why it needs to be base64 as they have tried L2FkbWluL215YWNjb3VudD9zaXRlPWRlZmF1bHQK
and it doesn't work 
Thanks

**Comment by dsmrt** [comment]
The plugin expects it to be base64. This is common with relaystate and other saml get parameter based messages to avoid encoding issues in the url. There is a config in the saml-sp.php that you can set to tell it to except non-base64’d strings if desired. 

I’d also recommend seeing what the logging says. If it’s not working as a base 64 string something is wrong in the process and there is logging around relaystate

**Comment by WITwebmaster** [comment]
Great thanks for the feedback , I am meeting the IT guys on Monday so I will pass on your answer and hopefully get it sorted

**Comment by WITwebmaster** [comment]
Sorry I forgot to close this one. In the end as my url  will never change, I went with the approach of taking the link button url and changing the final segment to point to the user page. I create a redirect called sitename/staffprofile and pointed it to that URL and it all works nicely. Thanks for the help

**Comment by WITwebmaster** [comment]
Sorry I forgot to close this one. In the end as my url  will never change, I  went with the approach of taking the link button url and changing the final segment to point to the user page. I create a redirect called sitename/staffprofile and pointed it to that URL and it all works nicely. Thanks for the help
