### ISSUE TITLE
AssertionConsumerServiceURL' in the SAML message must be a URI.

### ISSUE THREAD

**Issue by isoxz** [flipboxfactory/saml-sp#200]
Azure produces an error as follows: "AADSTS7500511: XML attribute 'AssertionConsumerServiceURL' in the SAML message must be a URI." After installing the latest plugin, I can see that the Assertion Consumer Services (ACS) Bindings is showing up as a relative path, i.e. /sso/login/blabla. Azure expects a full URL, like https://base/then/the/path. 

In the video provided I can see it shows absolute URL, so I thought it was my plugin install, and reinstalled it a couple of times on 2 separate boxes. Same result. ACS bindings show up as relative rather than absolute. I would be happy to help troubleshoot or test anything related to this. 

relevant screenshots:

![image (3)](https://github.com/flipboxfactory/saml-sp/assets/149834626/8103d0b3-6a85-41b3-b695-51c5847c8f9f)
![image (4)](https://github.com/flipboxfactory/saml-sp/assets/149834626/0de485dc-debd-4766-83bd-ca9207f8b9f2)

**Comment by dsmrt** [comment]
Take a look at the craft site assignment your service provider. Seems like there is no base url set on the site you've assigned to the provider (your provider).

**Comment by isoxz** [comment]
it worked perfectly. Thank you so much. To be clear: explicitly setting the baseURL under Settings->Sites to $site_URL instead of slash. Thank you so much for the super fast clue. Happy Holidays!
