### ISSUE TITLE
Stop automatic user creation

### ISSUE THREAD

**Issue by alexmillman23** [flipboxfactory/saml-sp#203]
Is there a way to stop the automatic creation of users? If a user is not found in Craft, we do not want a user account created with the fields sent from the IdP. 

Would like to stop the default behavior mentioned here:
https://github.com/flipboxfactory/saml-sp/issues/129#issuecomment-928039842

**Comment by dsmrt** [comment]
You can add a config to the `config/saml-sp.php`:
```php
return [
   'createUser' => false,
];

See https://github.com/flipboxfactory/saml-sp/blob/c1991f64aa77815f3671fd4435fca3d2d884ce93/src/models/Settings.php#L76

**Comment by alexmillman23** [comment]
Got it, thanks! Since this throws an exception and OneLogin does not get a response it expects, perhaps I need to handle this on the OneLogin side so users do not get an almost blank error screen.

Thanks for your quick response.

**Comment by dsmrt** [comment]
Closing this but let me know if you have any other questions
