### ISSUE TITLE
broken link to provider in SAML External Identity Fields

### ISSUE THREAD

**Issue by d--j** [flipboxfactory/saml-sp#206]
On a multis-site CraftCMS installation `baseProviderUrl` in https://github.com/flipboxfactory/saml-sp/blob/47d65155b2896f18436ade2d5191f261048ef310/src/templates/_cp/fields/external-id.twig#L22C29-L22C44 includes the current site (e.g. https://my-site.example.com/admin/saml-sp/metadata?site=siteRoot) This will produce broken links like https://my-site.example.com/admin/saml-sp/metadata?site=siteRoot/2.

Aside from this, the link should probably only be created when the current user is able to access the provider page (`currentUser.can('accessPlugin-saml-sp')`)

**Comment by dsmrt** [comment]
Good find @d--j 

Thanks for finding this and the help here!

I got a patch up in 4.1.0

**Comment by dsmrt** [comment]
Let me know if you have any issues with the update
