### ISSUE TITLE
Craft 5 Support

### ISSUE THREAD

**Issue by elivz** [flipboxfactory/saml-sp#210]
Now that Craft 5 is officially released, wanted to start a thread to get a sense for if/when you are planning to update the plugin for compatibility. Looks like most of the big changes are related to the whole Entrification situation, so hoping this one won't be too terrible.

**Comment by dsmrt** [comment]
Hi @elivz thanks for getting this conversation started. We have talked briefly about the effort and have a rough idea of the effort. We plan on getting this knocked out soon.

**Comment by elivz** [comment]
Amazing! Glad to hear it.

**Comment by dsmrt** [comment]
Pushed! https://github.com/flipboxfactory/saml-sp/pull/211

Checkout tagged version 5.0.0 🎉
