### ISSUE TITLE
Service Provider is not found. Possibly a configuration problem. My Provider/Current EntityId: 

### ISSUE THREAD

**Issue by rickardx** [flipboxfactory/saml-sp#224]
We followed the Azure AD instructions exactly (from the video) and everything looks good. But when trying to login I get the following error:

`Service Provider is not found. Possibly a configuration problem. My Provider/Current EntityId: https://{domain}/`

The Entity ID in the system is without the ending /

So error gives this: https://{domain}/
But the EntityID (My Provider) is: https://{domain}

This is the only thing I can think of? Also the certificate has not been sent to the client managing the Azure App.

**Comment by rickardx** [comment]
I fixed this by adding the / to my Entity ID.

**Comment by dsmrt** [comment]
Glad you were able to fix it!
