### ISSUE TITLE
Integration error (Tableau)

### ISSUE THREAD

**Issue by cole007** [flipboxfactory/saml-sp#25]
Trying to integrate with a third-party Service and followed instructions - however when I go to the Identity Provider to configure I get the following error:

```Exception 'Error' with message 'Call to a member function getAllSingleLogoutServices() on null' in /srv/users/serverpilot/apps/XXX/vendor/flipboxfactory/saml-core/src/controllers/cp/view/AbstractController.php:165 Stack trace: #0```

Is this an issue with how the XML meta file is setup that am importing?

**Comment by cole007** [comment]
The third-party service in question is Tableau. 
Relevant docs > https://onlinehelp.tableau.com/current/online/en-us/saml_config_site.htm

**Comment by dsmrt** [comment]
I just want to clarify. Are you wanting to use Tableau as your identity provider (the IDP)? Users are managed within Tableau and anyone using Craft would login thru Tableau?

**Comment by dsmrt** [comment]
To expand on my above comment, this plugin is on the service provider side (the SP), one which consumes the identities from another provider. It depends on an identity provider (IDP) like Microsoft ADFS, OneLogin, OKTA, providers like that. The docs you provided show how to setup SSO with an IDP so following those instructions won't work with this plugin.  

I hope this helps. SAML is extremely confusing so let me know if you need me to go into more detail.

**Comment by cole007** [comment]
So the premise is client wants a skinned login to their service via Craft so from your comments this wouldn't be possible unless we route this through a third-party service?

**Comment by cole007** [comment]
(thanks for response)

**Comment by cole007** [comment]
*Think* getting head round this - so in essence we are wanting to create an IdP locally to be consumed by a third-party SP (Tableau) whilst at present the `saml-sp` plugin is set up to work the other way round (the clue, I guess, is in the title)?

**Comment by dsmrt** [comment]
That is correct. At one point we had a plugin for saml-idp on the roadmap but we haven't really needed it yet. Feel free to contact us and we can talk more: https://www.flipboxdigital.com/contact
