### ISSUE TITLE
Trying to get property 'keychain' of non-object

### ISSUE THREAD

**Issue by nilsnh** [flipboxfactory/saml-sp#26]
Hi there. 👋 Thanks for the work on this plugin. :) I have configured this plugin on a remote server and when I tried to run it locally on my machine I ran into an issue. 

Steps to reproduce:

1. Setup identity provider and generate keychain on remote server. It did not make it encrypted at rest.
2. Do backup and download of remote database and run a copy locally. 
3. Try to login on `/admin` with the configured identity provider.

From the key chain configuration screen it seemed like the key would be stored in the database. But when logging in locally it seems to be missing.

![image](https://user-images.githubusercontent.com/282865/57602056-67c74900-755e-11e9-94b0-77b513af4fb2.png)

**Comment by dsmrt** [comment]
Hi @nilsnh, 

Looks like the actual Service Provider (craft's provider) needs to be configured. Try going to this admin cp page, within the craft admin: `<your host name>/admin/saml-sp/metadata/my-provider`. Is this configured? Reference my okta walk thru if needed: https://www.flipboxdigital.com/insights/configuring-saml-sp-with-okta-com

Let me know if this isn't the issue and we can dive in further.

The error handling could be better here, so I apologize for that.

**Comment by nilsnh** [comment]
Hi! I had configured a service provider, but the entity id was for the test server domain. So, when I made a copy and ran it locally as localhost it threw this error. It was fixed when I updated the entity id to be localhost. The error handling can be improved for sure, but I'll close this as solved. Thanks for the help. 😸
