### ISSUE TITLE
Doesn't work with Craftcms 3.2

### ISSUE THREAD

**Issue by punkch** [flipboxfactory/saml-sp#28]
Hello and thank you for the wonderful plugin.

I was trialing it with a new project and everything was working fine, until I upgraded to the recently released craftcms 3.2.2 update.

Attached is a screenshot from the error, but please let me know if I can provide you with more information.

![image](https://user-images.githubusercontent.com/1732172/61289919-d6c55600-a7ca-11e9-8e64-fe7c1e557308.png)

**Comment by dsmrt** [comment]
Hello! 👋

Thanks for finding this. I'll try and take a look within the next week or so. 

Just a heads up, I do have a 2.0 branch going and there are going to be some major breaking changes. This will probably be released in the next month or so. Mostly try and avoid any interactions in the code with the LightSaml lib.

**Comment by smockensturm** [comment]
Likewise. This is important.

**Comment by smockensturm** [comment]
And this is REALLY uncool for a 200 dollar plugin.

**Comment by dsmrt** [comment]
Totally understand @smockensturm. I can get a patch out today.

**Comment by smockensturm** [comment]
Updated to 1.0.7. Still not good.







yii\base\ErrorException: Trying to get property 'keychain' of non-object in /home/vagrant/sites/tnt/vendor/flipboxfactory/saml-sp/src/services/messages/AuthnRequest.php:76
Stack trace:
#0 /home/vagrant/sites/tnt/vendor/craftcms/cms/src/web/ErrorHandler.php(81): yii\base\ErrorHandler->handleError(8, 'Trying to get p...', '/home/vagrant/s...', 76)
#1 /home/vagrant/sites/tnt/vendor/flipboxfactory/saml-sp/src/services/messages/AuthnRequest.php(76): craft\web\ErrorHandler->handleError(8, 'Trying to get p...', '/home/vagrant/s...', 76, Array)
#2 /home/vagrant/sites/tnt/vendor/flipboxfactory/saml-sp/src/controllers/LoginController.php(120): flipbox\saml\sp\services\messages\AuthnRequest->create(Object(flipbox\saml\sp\records\ProviderRecord))
#3 [internal function]: flipbox\saml\sp\controllers\LoginController->actionRequest(NULL)
#4 /home/vagrant/sites/tnt/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#5 /home/vagrant/sites/tnt/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#6 /home/vagrant/sites/tnt/vendor/craftcms/cms/src/web/Controller.php(187): yii\base\Controller->runAction('request', Array)
#7 /home/vagrant/sites/tnt/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('request', Array)
#8 /home/vagrant/sites/tnt/vendor/craftcms/cms/src/web/Application.php(299): yii\base\Module->runAction('saml-sp/login/r...', Array)
#9 /home/vagrant/sites/tnt/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('saml-sp/login/r...', Array)
#10 /home/vagrant/sites/tnt/vendor/craftcms/cms/src/web/Application.php(284): yii\web\Application->handleRequest(Object(craft\web\Request))
#11 /home/vagrant/sites/tnt/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#12 /home/vagrant/sites/tnt/public/index.php(21): yii\base\Application->run()
#13 {main}

**Comment by smockensturm** [comment]
Ah. Never mind. Local environment changed. Looks OK deployed.

**Comment by dsmrt** [comment]
@punkch and @smockensturm 
Please run an update to both saml-sp and saml-core.
Run `composer update flipboxfactory/saml-sp flipboxfactory/saml-core` and make sure you are on saml-sp:1.0.8 and saml-core:1.0.2 for Craft 3.2 fixes.

Download them here:
https://github.com/flipboxfactory/saml-core/releases/tag/1.0.2
https://github.com/flipboxfactory/saml-sp/releases/tag/1.0.8
