### ISSUE TITLE
2.0 Upgrade - Login error

### ISSUE THREAD

**Issue by darksaboteur** [flipboxfactory/saml-sp#31]
I have upgraded version 1.0.8 to 2.0.2 and now receive the following error when clicking the "Via XXXXX" button on the login screen. Is this a bug in the update or a misconfiguration on my end?

![saml-2 0 2-error](https://user-images.githubusercontent.com/10037552/65286395-c347ba00-db82-11e9-82b4-dffbb1dcdcc2.png)

**Comment by dsmrt** [comment]
Hi @darksaboteur ... sorry you are seeing this issue.

Can you trying running `composer update flipboxfactory/saml-core` and see if that updates?

Also, take a look here for more upgrade info: https://saml-sp.flipboxfactory.com/installation.html#upgrading-to-2-0

**Comment by dmatthams** [comment]
Also getting this error in 2.0.2, but not sure if it is related to my other issue #32. Have saml-core up to date.

**Comment by dsmrt** [comment]
Found the issue here. Working on a patch!

**Comment by dsmrt** [comment]
Fixed in 2.0.3. Run a `composer update flipboxfactory/saml-sp` and see how that looks.
