### ISSUE TITLE
Integration with Azure AD

### ISSUE THREAD

**Issue by benjaminkohl** [flipboxfactory/saml-sp#37]
This might be an issue with me not being a SAML expert, but the people that are responsible for managing our client's Azure AD SSO are asking me for redirect URIs for: identity, callback and logout. They said once they get that, they can provide the application ID, client secrets, metadata and token endpoint.

Unless I am mistaken, these sound more like OAuth terms rather than SAML terms. But what do I know? I specifically mentioned SAML in my email to them so I am feeling a bit lost. Are there instructions online for configuring the plugin's settings with Azure AD?

**Comment by dsmrt** [comment]
Great question! Going to pin this because I've got a lot of AD questions lately. 

I'm not sure what they mean by `identity` but here's what I found after some quick testing.

There are a few things you need to pass along:
1. The certificate for your provider. You can download that from the "My Provider" security tab (/admin/saml-sp/metadata/my-provider#security)
2. Assertion Consumer Service (ACS) Endpoint. I believe this is what they mean by the callback. It will be something like this: `https://my-sp.domain.com/sso/login`
3. Single logout/SLO Endpoint: `https://my-sp.domain.com/sso/logout`

Once they create the App, ask them to send you the metadata (like normal) but also the Application ID. The application ID needs to be your entity id now. You can overwrite that system-wide by setting it here: `/admin/saml-sp/settings` (it can be an environmental variable). Once you set that, you need to recreate "My Provider" so the new entity id is picked up and saved in the plugin correctly.

I think that is it but let me know if you run into any issues.

**Comment by dsmrt** [comment]
Side note on mappings....

You can view the metadata to identify the attributes passed on to you. They will look like these:

- `http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname`
- `http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname`
- `http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress`

You can configure the IdP like so:

![Screen Shot 2019-10-02 at 1 07 02 PM](https://user-images.githubusercontent.com/1995478/66074288-225be600-e516-11e9-82e8-e2c41ddec6c6.png)

**Comment by benjaminkohl** [comment]
Great, thank you! We will definitely need to store some of the attributes to the user profile so that will be helpful as well. I'll get back to the client and see what they say and go from there.

**Comment by benjaminkohl** [comment]
The person responsible for our client's Azure AD SSO got back to me with an application ID (uuid), a client secret and a link to the XML metadata. I think all I need is that XML metadata, right? Otherwise I am not sure where that UUID or client secret play into SAML.

**Comment by dsmrt** [comment]
Application ID is important here. You need to make the Application ID your Entity ID now. Currently, the best way to overwrite this is to set it system wide here: `/admin/saml-sp/settings`. Note that you can set that as an environmental variable. Once that is set make sure to either resave or delete and save a new "My Provider".

**Comment by benjaminkohl** [comment]
I am unable to save the provided application ID to that entity field. I copy and paste it in then click the "Save" button to update the plugin settings and I get the following exception and stack trace:

```
2019-10-14 09:46:07 [-][9][e8c528f73c65c856b36b93190d958eeb][error][yii\base\InvalidConfigException] yii\base\InvalidConfigException: Object configuration must be an array containing a "class" element. in /home/user/site.com/hub/prod/vendor/yiisoft/yii2/BaseYii.php:353
Stack trace:
#0 /home/user/site.com/hub/prod/vendor/yiisoft/yii2/base/Component.php(750): yii\BaseYii::createObject(Array)
#1 /home/user/site.com/hub/prod/vendor/yiisoft/yii2/base/Component.php(734): yii\base\Component->attachBehaviorInternal('error', Array)
#2 /home/user/site.com/hub/prod/vendor/yiisoft/yii2/base/Component.php(603): yii\base\Component->ensureBehaviors()
#3 /home/user/site.com/hub/prod/vendor/yiisoft/yii2/base/Controller.php(274): yii\base\Component->trigger('beforeAction', Object(yii\base\ActionEvent))
#4 /home/user/site.com/hub/prod/vendor/yiisoft/yii2/web/Controller.php(164): yii\base\Controller->beforeAction(Object(yii\base\InlineAction))
#5 /home/user/site.com/hub/prod/vendor/craftcms/cms/src/web/Controller.php(143): yii\web\Controller->beforeAction(Object(yii\base\InlineAction))
#6 /home/user/site.com/hub/prod/vendor/yiisoft/yii2/base/Controller.php(155): craft\web\Controller->beforeAction(Object(yii\base\InlineAction))
#7 /home/user/site.com/hub/prod/vendor/craftcms/cms/src/web/Controller.php(187): yii\base\Controller->runAction('save', Array)
#8 /home/user/site.com/hub/prod/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('save', Array)
#9 /home/user/site.com/hub/prod/vendor/craftcms/cms/src/web/Application.php(299): yii\base\Module->runAction('saml-sp/setting...', Array)
#10 /home/user/site.com/hub/prod/vendor/craftcms/cms/src/web/Application.php(566): craft\web\Application->runAction('saml-sp/setting...', Array)
#11 /home/user/site.com/hub/prod/vendor/craftcms/cms/src/web/Application.php(278): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#12 /home/user/site.com/hub/prod/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#13 /home/user/site.com/hub/prod/public/index.php(26): yii\base\Application->run()
#14 {main}
2019-10-14 09:46:07 [-][9][e8c528f73c65c856b36b93190d958eeb][info][application] $_GET = [
    'p' => 'admin/saml-sp/settings'
]
```
This is version 2.0.9 of the plugin and version 3.3.9 of Craft.

**Comment by dsmrt** [comment]
Working on a patch for this now.

**Comment by dsmrt** [comment]
Should be good now. Try running a `composer update flipboxfactory/saml-sp`. The core lib should update as well.

**Comment by benjaminkohl** [comment]
Ok, it let me save the settings and per these instructions (_WARNING: If this value is changed, you must recreate "My Provider" and exchange the metadata or values with the other provider (IdP or SP)._), I went into my provider and re-saved so now I have two providers in the Service Provider List on the Provider List page.

So now I need to grab the metadata XML provided by our client managing the IDP again and paste it into that box for this newly created service provider?

**Comment by dsmrt** [comment]
Nope. Just recreate the SP (your provider). So go back to my provider (here: /admin/saml-sp/metadata/my-provider) and save a new one. You'll probably see 2 now. You can delete the one that doesn't match the new entity id/azure AD application id which should be the old one. 

Hopefully all of that makes a little sense. Azure wants the Entity ID to be the application id and currently the only way to do that is to set it system wide. When you set that value system-wide, you have to recreate you metadata and save (what happens when you save from /admin/saml-sp/metadata/my-provider) so everything in the craft db is updated.

**Comment by benjaminkohl** [comment]
There is a read-only field for Login Path and it instructed me to place that value as the loginPath item in the general config file. I grabbed the relative URI from that value and placed it in there. When I try to access the site and it redirects to that login path, I just see the 404 page.

The URL it told me to use looks like: `sso/login/{uuid}`

**Comment by dsmrt** [comment]
Ok ... try adding `request` into the path like so: `/sso/login/request/{uid}`

I'll push a patch for that readonly field.

**Comment by benjaminkohl** [comment]
Ok, thanks. Now I see it performing some redirects but I end up at the Craft error screen for "Bad Request" with the following message:
```
Identity Provider is not found. Possibly a configuration problem. Issuer/EntityId: https://sts.windows.net/{different uuid that came from provider metadata xml}/
```

**Comment by dsmrt** [comment]
Do you see that entity id in the provider list under IdPs? If not, create the idp in the craft plugin with the Azure AD metadata. You should see the entity id there: 
![Screen Shot 2019-10-15 at 2 56 05 PM](https://user-images.githubusercontent.com/1995478/66869337-6ca08680-ef5c-11e9-9c56-db8989a0a4d0.png)

**Comment by dsmrt** [comment]
Are you sure the fields are configured correctly? Is the email address point to `Email` in the craft property column like so? I've made the mistake of not setting that correctly and seeing this error.

![Screen Shot 2019-10-02 at 1 07 02 PM](https://user-images.githubusercontent.com/1995478/66935811-e9ce0900-eff9-11e9-9c6e-ec444ec6d128.png)

**Comment by benjaminkohl** [comment]
Yes, that is set correctly. I've also proofread the Attribute Name a few times to make sure I typed it correctly. I'm not spotting any inconsistencies but just in case, here it is:

> http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress

**Comment by benjaminkohl** [comment]
I am currently looking at [this documentation](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-saml-claims-customization). Perhaps the people managing the account haven't configured it to provide the email address. I'll get in touch with them and see what they say.

**Comment by dsmrt** [comment]
Ok cool ... Also try using this tail grep command. You should be able to see the attributes or the plugin debug looking for the attributes in there.

```tail -f storage/logs/web.log | grep -A 10 -n '\[saml-'```

**Comment by benjaminkohl** [comment]
I found that they are sending the email address in the "name" attribute so I updated the plugin settings and I was able to successfully log in. Thanks for all the help with this! It has been very much appreciated.

**Comment by dsmrt** [comment]
I'm going to close this but feel free to reopen if needed, on AD specific stuff.

**Comment by espensgr** [comment]
We have a setup with Craft as a admin backend, with multisite, that acts like an api for generated static Nuxt as frontend.
All of the sites (1 backend and 2 frontend) have different domains and the users should only login to the backend.
How do i setup so the `loginPath` goes to the backend?
When i have tried to set it up it goes to the frontend domain with /sso/login.
My first time adding an SSO, and the costumer haven't used Azure that much either :flushed:

**Comment by dsmrt** [comment]
@espensgr moved your question to it's own issue. I think this is more of a static site issue to tackle than an Azure AD issue.

See #101

**Comment by dsmrt** [comment]
This issue is no longer the best "instructions" when configuring Azure AD. I've updated the docs based on updates to the plugin here 👉 [Azure AD](https://saml-sp.flipboxfactory.com/configure/idps/azure-ad.html). Please follow those instructions moving forward.

**Comment by espensgr** [comment]
I still think the steps and documentation is a bit confusing for someone that hasen't setup SSO before.
Is it possible to make a video click-walkthrough on how to setup this with Azure AD, or maybe other ones too? It may just be my peanut sized brain though 🤣

**Comment by dsmrt** [comment]
That would be nice. I think i could get something like that going. 

Also, lack of understanding has nothing to do with size of brain. SAML was built by alien’s to confuse humans and hinder progress. It’s confusing. 

I’ll look into the video thing. I think it’d be nice to have a resource like that. Especially with Azure AD.

**Comment by espensgr** [comment]
Nice!

Yeah, i actually think that SAML stands for Sampling Alien Management Licence, so you are correct.
