### ISSUE TITLE
Add Link/Button to Initiate IDP Login via the Craft CP Login Page

### ISSUE THREAD

**Issue by dsmrt** [flipboxfactory/saml-sp#4]
Currently, the only way to login via the IDP is through a frontend template, ie, `/login`. Ideally, users will utilize this plugin for frontend and backend authentication so the goal here is to simply add a link or button to the cp login page so there is a way to initiate login from there. Considerations must be made for the `RelayState` so the user is correctly redirected to the page they were attempting to goto in the first place after authentication.

**Comment by jeffsikes** [comment]
Some of the backend administration areas require you to re-enter your password in order to continue - how would that be handled via SSO?  Example: Clicking the Save button on the Add New User form.

![image](https://user-images.githubusercontent.com/6627582/44174410-ae0f7a80-a0a8-11e8-89c4-60de06fc2613.png)

**Comment by nateiler** [comment]
Ah yes.  This is considered an 'Elevated Session'.  The SAML protocol might break this as checking the IDP would likely result in a redirect.

Thinking...

**Comment by dsmrt** [comment]
I believe this sort of Craft customization is "in the works". Looks like the AuthManager.js manages that modal and is referenced here: https://github.com/craftcms/cms/issues/1471#issuecomment-407034303. I've commented there as well and showed my update that we are working on for the `/admin/login` page.

Here is my screenshot for the login page.
![screen shot 2018-08-13 at 8 48 11 am](https://user-images.githubusercontent.com/1995478/44177486-6ccc9a00-a0ab-11e8-990d-65de443c37f8.png)

**Comment by nateiler** [comment]
Thinking it might be possible to create a new elevated session manager class and override the `Craft.elevatedSessionManager` found `/src/web/assets/cp/src/js/ElevatedSessionManager.js:156`

Probably also have to consider something for login timeout.

**Comment by m8i** [comment]
I see that you've got this mostly completed. How do I make a friendly name for this? In your screenshot, it shows "Via OKTA," but mine shows an ugly URL. :)
![2018-10-01_17-26-50](https://user-images.githubusercontent.com/9837300/46319414-93815a00-c59f-11e8-82ff-c95e861fad6a.jpg)

**Comment by dsmrt** [comment]
I added labels to the providers on the edit view. You can name them whatever you want. I suggest in the documentation to use environment if you are managing more than one but you can name it however you choose. 

Let me know if there is anything else!

**Comment by dsmrt** [comment]
Closing this due to limitations with our options here.

**Comment by mihow** [comment]
Did this get partially implemented? I see the "login via" button on the Craft CMS login screen.

![image](https://user-images.githubusercontent.com/158175/71939961-5116d780-3169-11ea-9580-ad02ca86c98b.png)

**Comment by dsmrt** [comment]
@mihow Yes it did. That will initiate login.
