### ISSUE TITLE
Custom SAML attributes in response

### ISSUE THREAD

**Issue by benjaminkohl** [flipboxfactory/saml-sp#40]
I have another question regarding the SAML attributes. It has been brought to our attention by the client that some of the attributes we need to pull from the SAML response are not default attributes and they have to be specifically requested in order to show up in the response. Does the plugin include the list of requested attributes in the request to the IDP?

I know this is something I should just be able to test and determine on my own but I'm having trouble getting the actual names of these attributes from the client. I've been guessing up to this point but I am hoping to get a definitive list from them soon.

**Comment by dsmrt** [comment]
Great question! The plugin doesn't currently pay attention to the ClaimTypes and Attributes in the Metadata but it would be nice as a feature. My only hesitation is, those elements in the metadata are optional and Microsoft ADFS may be the only one who uses them.

Couple things you can try here: 
- Check out the metadata for the IdP. You can look at "Attributes"  or "ClaimType" nodes to see what may be available.  They might be in there.
- Checkout the logging: `tail -f storage/logs/web.log | grep -A 10 -n '\[saml-sp\]'`. You should be able to see a log line like the following when logging-in: ```2019-11-07 22:07:48 [-][2][-][trace][saml-sp] assertion attributes: {"FirstName":["damien"],"LastName":["smrt"],"Email":["me@dsmrt.com"]}

**Comment by benjaminkohl** [comment]
I've done that after one of our discussions in a previous issue. I've also grabbed the entire SAML response and formatted it so I could view all the attributes. The ones I need aren't in there and they told me they wouldn't be. Of course, I don't know what their exact names will be but I would know them when I see them. It's been quite a task.

**Comment by dsmrt** [comment]
OK ... Similarly to the cert issue, I only grab the first assertion. I've never seen multiple assertions used so I just kept it easy. I wonder if there's multiple assertions coming back. Take a look at the xml and see if that is the case. I just looked at the code and, if that is the issue, it should be a simple patch. I'll work on getting that patch up regardless. Maybe today, if not tomorrow.

**Comment by benjaminkohl** [comment]
I only see one assertion in each response and these are the only attributes that appear:
```
http://schemas.microsoft.com/identity/claims/tenantid
http://schemas.microsoft.com/identity/claims/objectidentifier
http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name
http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname
http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname
http://schemas.microsoft.com/identity/claims/displayname
http://schemas.microsoft.com/identity/claims/identityprovider
http://schemas.microsoft.com/claims/authnmethodsreferences
```

**Comment by dsmrt** [comment]
Ok, if that is the case, they don't seem to be sending it. I pushed up a patch for gracefully handling all assertions (instead of just the first). You might want to pull that down (`composer update flipboxfactory/saml-sp`) and see if that helps but if you aren't seeing more assertions or attributes in the response, they aren't sending the properties over.

**Comment by benjaminkohl** [comment]
Thanks for looking into this. I really appreciate all your help. I get the feeling I've been pushed in the wrong direction regarding this issue; I found an Azure AD article that states they can configure these custom claims from the portal on a per-app basis. I believe this is what they (or whoever has control over their account) should be doing. Once those attributes appear in the SAML response, I can just figure out their correct names from the log just like you have shown.

Again, thank you for all the help!

**Comment by dsmrt** [comment]
Sounds good and no prob. Going to close this for now. Reach out again if you need.
