### ISSUE TITLE
SSO HTTP-Redirect Binding Support

### ISSUE THREAD

**Issue by dennismeissner** [flipboxfactory/saml-sp#41]
Hey, there is a statement in your Code which says:

https://github.com/flipboxfactory/saml-sp/blob/7c15e2af4d79e334a1f0a87139060891897cfca3/src/services/messages/AuthnRequest.php#L33

Is there a plan to fix this soon? 
Actually at the moment it fails with the following message:
```Call to a member function getLocation() on null``` 

if i replace ```Constants::BINDING_HTTP_POST``` with ```Constants::BINDING_HTTP_REDIRECT``` it works for me.

my metadata snapshot:
```
...
    <md:SingleLogoutService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect" Location="https://-----/simplesaml/saml2/idp/SingleLogoutService.php"/>
    <md:NameIDFormat>urn:oasis:names:tc:SAML:2.0:nameid-format:transient</md:NameIDFormat>
    <md:SingleSignOnService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect" Location="https://-----/simplesaml/saml2/idp/SSOService.php"/>
```

**Comment by dsmrt** [comment]
Done. Find it in version 2.0.13.
