### ISSUE TITLE
Azure AD configuration problem, Service Provider not found

### ISSUE THREAD

**Issue by AndreasNaustdal** [flipboxfactory/saml-sp#44]
Hi, I’m trying to set up SSO for Azure Active Directory users to log in to craft. I have followed the setup, creating SP and generating key pair. The organization which use Azure AD, has sent me the XML which I pasted into the IdP metadata. When I click the “Via Active Directory” login button I get the following error:

Service Provider is not found. Possibly a configuration problem.
My Provider/Current EntityId: http://{url-to-website}/  

Not sure if it is the SP or IdP which is not set up correctly, which part of the configuration is bad?
I have tried to delete all configuration and do the setup again, with same result

Craft version: 3.3.15 (PRO license)
SAML Service Provider version: 2.0.10

**Comment by dsmrt** [comment]
Check the listing here: /admin/saml-sp/metadata

There is an Entity ID column on that page and you should be see that Entity ID in that list. If you don't, it may be an environmental issue or you may need to follow these instructions on how to make things work correctly with Azure AD: https://github.com/flipboxfactory/saml-sp/issues/37#issuecomment-537633890

**Comment by AndreasNaustdal** [comment]
The Entity ID is in the column, it is the same except it is https, and the error is http. Could that be a problem? I also see that I have not sent the SP certificate.

**Comment by AndreasNaustdal** [comment]
Sending certificate and receiving application ID to put into /admin/saml-sp/settings, and then recreating the SP solved the error

**Comment by dsmrt** [comment]
Http vs Https would be an issue. Glad it worked out. Let me know if you have any other questions!
