### ISSUE TITLE
No message is displayed or logged when SAML fails

### ISSUE THREAD

**Issue by mihow** [flipboxfactory/saml-sp#50]
When initiating login from the CP login page, if something about the sign-in fails the user is redirected back to the the login page with no message and there is no information available in the Craft logs. 

Currently I am able to use OneLogin in our dev environment but not in production and I have no way of troubleshooting the issue. 

I am able to replicate this locally if I set the "SAML Consumer URL" to an incorrect URL. The sign-in fails but there is no information provided as to why.

![image](https://user-images.githubusercontent.com/158175/73030989-b9172000-3def-11ea-91da-f257bda23404.png)

**Comment by dsmrt** [comment]
Can you tail the logs and see if there's anything in there?

```
tail -f storage/logs/web.log| grep -A 5 '\[saml-'
```

**Comment by mihow** [comment]
Unfortunately I'm not seeing anything in any of these log files
```
storage/logs/craft.log
storage/logs/web.log
storage/runtime/logs/app.log 
storage/logs/phperrors.log
storage/logs/console.log
storage/logs/queue.log 
```

**Comment by dsmrt** [comment]
Couple things. 
1. If you can replicate it on local then see what the logs look like on local. Or turn devMode on prod and for testing. 
2.  On most common errors we throw exceptions so you should see some message. 
3. When devMode is on you should be able to see the response come through in the logging. That might be a good place to start looking. 
4. Are you getting redirected to OneLogin?

**Comment by mihow** [comment]
Thanks, I am unable to replicate on local. The login works fine there. I can't turn on devMode in production but I will fire up another remote environment where I can and will test there. And yes, we are getting directed to OneLogin (https://***.onelogin.com/trust/saml2/http-post/sso/314dbcf6-e1dd-449d-8998-ed5dbabca3b2) and then back to the admin login page.

**Comment by dsmrt** [comment]
Just trying to understand what you are seeing. Here are the steps to recreate:

1. Go to the Craft CMS CP login (ie, `/admin/login`)
2. Click the login button, `Via OneLogin`
3. Redirected to OneLogin, login successfully, then returned to the Craft CMS CP login

There's no error and you aren't logged in. You just see the login screen.

Does the "SAML Consumer URL" in OneLogin have "admin" into? like `https://example.com/admin/sso/login`

**Comment by mihow** [comment]
Yes, that's exactly what's happening.

The SAML Consumer URL does _not_ contain `/admin/`. Should it? Currently it looks like this:
https://example.com/sso/login

When I change it to
https://example.com/admin/sso/login 

We see this error

![image](https://user-images.githubusercontent.com/158175/73332435-9637a200-421b-11ea-96e1-b51401a46eb4.png)

**Comment by dsmrt** [comment]
Ok ... I think I got it! No admin shouldn't be in there.

I was able to replicate this. I think you have multiple service providers installed so the OneLogin URL is sending you back, logging you in, then redirecting you to where you were trying to go before.

Your login page *needs* to be the same domain on prod (https://example.com/admin/login) as the "consumer url" in OneLogin. This need to match exactly. (https://example.com, https://www.example.com).

Within the plugin, delete the sp provider that matches the URL/domain to the current consumer URL. You'll then see that things are not configured correctly.

**Comment by dsmrt** [comment]
One thing you can do to debug this is open up your browser network console and view the redirects. You might have to preserve logs.

When debugging, I saw, something like this:
```
https://sp.localhost/admin/login (clicked button on this page)
https://myidp.com/saml/sso/id (logged in)
https://localhost/sso/login (notice the hostname is different here)
https://sp.localhost/admin/login (the plugin redirects me to where I was trying to go, like /admin/dashboard)
```

**Comment by mihow** [comment]
Thanks! I thought I have the hostname and entity ID correct but I
will double  check today.

Have you seen any examples of someone using the plugin with OneLogin? They
use different names for the configuration fields than Okta or other
examples I’ve seen.

**Comment by dsmrt** [comment]
Every SAML provider is different which is frustrating. I use use the metadata because it has everything you need in it and I don't understand why everyone doesn't do that. 

Here is a screenshot on how I configured my testing OneLogin account.

![Screen Shot 2020-01-29 at 10 38 30 AM](https://user-images.githubusercontent.com/1995478/73382304-7d170b80-4284-11ea-95df-9a13524266f6.png)

**Comment by dsmrt** [comment]
Closed this for now but let me know if you have any more issues.

**Comment by mihow** [comment]
Thanks for your help. I am starting to believe our configuration with Craft & OneLogin is okay, however something with the frontend server (in Nginx or Heroku itself) is getting in the way. Everything works locally just fine, even when I use a remote hostname with Ngrok over HTTPs.
