### ISSUE TITLE
Updating from 1.x to 2.x on Craft 3.4 migration error

### ISSUE THREAD

**Issue by darksaboteur** [flipboxfactory/saml-sp#51]
`www-data@05f835653e05:~/html$ ./bin/craft migrate/all
Yii Migration Tool (based on Yii v2.0.32)

    > add column groupOptions text to table {{%saml_sp_providers}} ... done (time: 0.087s)
    > add column syncGroups boolean NOT NULL DEFAULT TRUE to table {{%saml_sp_providers}} ... done (time: 0.045s)
    > add column groupsAttributeName string(64) DEFAULT 'groups' to table {{%saml_sp_providers}} ... done (time: 0.058s)
    > add column encryptAssertions boolean NOT NULL DEFAULT FALSE to table {{%saml_sp_providers}} ... done (time: 0.073s)
    > add column encryptionMethod string(64) NULL DEFAULT NULL to table {{%saml_sp_providers}} ... done (time: 0.075s)
    > add column nameIdOverride text to table {{%saml_sp_providers}} ... done (time: 0.063s)
Exception: Undefined property: flipbox\saml\sp\records\ProviderRecord::$metadataOptions (/var/www/html/vendor/flipboxfactory/saml-core/src/records/AbstractProvider.php:276)
#0 /var/www/html/vendor/flipboxfactory/saml-core/src/records/AbstractProvider.php(276): yii\base\ErrorHandler->handleError(8, 'Undefined prope...', '/var/www/html/v...', 276, Array)
#1 /var/www/html/vendor/flipboxfactory/saml-core/src/records/AbstractProvider.php(267): flipbox\saml\core\records\AbstractProvider->hasJsonProperty('metadataOptions')
#2 /var/www/html/vendor/flipboxfactory/saml-core/src/records/AbstractProvider.php(217): flipbox\saml\core\records\AbstractProvider->hasMetadataOptions()
#3 /var/www/html/vendor/yiisoft/yii2/base/Component.php(139): flipbox\saml\core\records\AbstractProvider->getMetadataOptions()
#4 /var/www/html/vendor/yiisoft/yii2/db/BaseActiveRecord.php(298): yii\base\Component->__get('metadataOptions')
#5 /var/www/html/vendor/flipboxfactory/saml-core/src/records/AbstractProvider.php(82): yii\db\BaseActiveRecord->__get('metadataOptions')
#6 /var/www/html/vendor/yiisoft/yii2/db/BaseActiveRecord.php(794): flipbox\saml\core\records\AbstractProvider->beforeSave(false)
#7 /var/www/html/vendor/yiisoft/yii2/db/ActiveRecord.php(676): yii\db\BaseActiveRecord->updateInternal(NULL)
#8 /var/www/html/vendor/yiisoft/yii2/db/BaseActiveRecord.php(681): yii\db\ActiveRecord->update(true, NULL)
#9 /var/www/html/vendor/flipboxfactory/saml-core/src/migrations/m190516_200148_attribute_typo.php(29): yii\db\BaseActiveRecord->save()
#10 /var/www/html/vendor/craftcms/cms/src/db/Migration.php(52): flipbox\saml\core\migrations\m190516_200148_attribute_typo->safeUp()
#11 /var/www/html/vendor/craftcms/cms/src/db/MigrationManager.php(233): craft\db\Migration->up(true)
#12 /var/www/html/vendor/craftcms/cms/src/db/MigrationManager.php(153): craft\db\MigrationManager->migrateUp(Object(flipbox\saml\sp\migrations\m190516_200148_attribute_typo))
#13 /var/www/html/vendor/craftcms/cms/src/services/Updates.php(233): craft\db\MigrationManager->up()
#14 /var/www/html/vendor/craftcms/cms/src/console/controllers/MigrateController.php(259): craft\services\Updates->runMigrations(Array)
#15 [internal function]: craft\console\controllers\MigrateController->actionAll()
#16 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#17 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#18 /var/www/html/vendor/yiisoft/yii2/console/Controller.php(164): yii\base\Controller->runAction('all', Array)
#19 /var/www/html/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('all', Array)
#20 /var/www/html/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('migrate/all', Array)
#21 /var/www/html/vendor/craftcms/cms/src/console/Application.php(87): yii\console\Application->runAction('migrate/all', Array)
#22 /var/www/html/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('migrate/all', Array)
#23 /var/www/html/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(craft\console\Request))
#24 /var/www/html/bin/craft(22): yii\base\Application->run()
#25 {main}
Exception 'craft\errors\MigrateException' with message 'An error occurred while migrating SAML Service Provider.'

in /var/www/html/vendor/craftcms/cms/src/services/Updates.php:241

Stack trace:
#0 /var/www/html/vendor/craftcms/cms/src/console/controllers/MigrateController.php(259): craft\services\Updates->runMigrations(Array)
#1 [internal function]: craft\console\controllers\MigrateController->actionAll()
#2 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#3 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#4 /var/www/html/vendor/yiisoft/yii2/console/Controller.php(164): yii\base\Controller->runAction('all', Array)
#5 /var/www/html/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('all', Array)
#6 /var/www/html/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('migrate/all', Array)
#7 /var/www/html/vendor/craftcms/cms/src/console/Application.php(87): yii\console\Application->runAction('migrate/all', Array)
#8 /var/www/html/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('migrate/all', Array)
#9 /var/www/html/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(craft\console\Request))
#10 /var/www/html/bin/craft(22): yii\base\Application->run()
#11 {main}`

Let me know of any other details you need

**Comment by dsmrt** [comment]
Got it. 

What version is flipboxfactory/saml-sp and flipboxfactory/saml-core?

Just to clarify, you got the exception during the migration?

**Comment by darksaboteur** [comment]
Thanks for the speedy response.
saml-core is 2.1.1.1 and saml-sp is 2.1.1.2

Yes running the migrations from the web interface or by manually running `craft migrate/all` results in the error

**Comment by dsmrt** [comment]
Ok cool ... I think I have an idea of what is going on here. I can probably take a deeper look in the next few days. I'll keep you updated.

**Comment by dsmrt** [comment]
I have a patch in saml-sp and saml-core 2.1.2. Take a look and let me know if you have any issues.
