### ISSUE TITLE
Some SAML assertion attributes not being mapped

### ISSUE THREAD

**Issue by eheiser** [flipboxfactory/saml-sp#56]
I've got the SSO working fine but for whatever reason the first and lastname of the user aren't being imported. Email address is imported correctly. The first and lastname are present in the saml response (see screenhots). Any idea/suggestions why they're not being imported?

![screenshot_01](https://user-images.githubusercontent.com/86934/79215716-48aaf880-7e4c-11ea-90f2-291793ec283c.jpg)
![screenshot_02](https://user-images.githubusercontent.com/86934/79215721-4d6fac80-7e4c-11ea-885d-5d1d658bdfdd.jpg)
![screenshot_03](https://user-images.githubusercontent.com/86934/79215723-4d6fac80-7e4c-11ea-84bf-8dd9b8afc60b.jpg)

**Comment by dsmrt** [comment]
I can't replicate this. Couple things come to mind: 

1. Do you have multiple SPs (my provider) enabled? Make sure to disable any providers that shouldn't be available on that environment. This just helps with making sure the correct provider is being picked up.
2. Are you using any events hooking into the plugin or a `config/saml-sp.php` or are you using the project config? If you are using the project config can you copy the saml-sp section here? (remove any sensitive data please).
3. Check the logs. You can grep the logs to find more details on how the attributes are being assigned: 
```shell 
tail -f storage/logs/web.log | grep '\[saml-'
```
You'll see the attribute map that's being used and the attribute being or not being mapped.

![Screen Shot 2020-04-14 at 9 27 54 AM](https://user-images.githubusercontent.com/1995478/79243168-7e42e800-7e32-11ea-9740-d7b76aeaeffe.png)

**Comment by eheiser** [comment]
Damien,

just wanted to let you know that after some additional testing things are
up and running for us.
Thank you for getting back to me, really appreciate it.
Stay safe!
Erwin

Erwin Heiser | Focus! bvba
focus-webdesign.be | erwin.heiser@gmail.com
+ 32 (0)4 87 544 302  | skype: stookstudio

**Comment by dsmrt** [comment]
Awesome! let me know if there's anything else we can help with!
