### ISSUE TITLE
Issue with with Single Logout Configuration

### ISSUE THREAD

**Issue by eheiser** [flipboxfactory/saml-sp#57]
We still have a problem with the configuration of the “Craft SAML SSO Service Provider” plugin.
It looks like the “Single Logout Service (SLO) Binding” isn’t detected from the metadata:
(screenshot1)
The Metadata URL we are using is https://auth.vincotte.be/samlp/metadata/mAbNvxaV1H6DeOK5C1at2DGviwAOA2e9

As shown in the screenshot below this metadata does contain a “SingleLogoutService” tag with binding “urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect”.
(screenshot2
![screenhot1](https://user-images.githubusercontent.com/86934/81075431-a631e280-8eea-11ea-8adc-dcb42507e1e0.png)
![screenshot2](https://user-images.githubusercontent.com/86934/81075441-a8943c80-8eea-11ea-90e6-0b9d00cc2e9e.png)

)
If you'd like an admin account to take a look please let me know.

**Comment by dsmrt** [comment]
Got it! I have a patch up in 2.1.6.

**Comment by eheiser** [comment]
Awesome - thanks!

Erwin Heiser | Focus! bvba
focus-webdesign.be | erwin.heiser@gmail.com
+ 32 (0)4 87 544 302  | skype: stookstudio

**Comment by eheiser** [comment]
Added the patch but we're still running into the same issue.
Check the public url https://auth.vincotte.be/samlp/metadata/mAbNvxaV1H6DeOK5C1at2DGviwAOA2e9

**Comment by dsmrt** [comment]
What issue are you seeing. Is SLO not working? Do you have an error?

**Comment by dsmrt** [comment]
Actually, one thing I didn’t mention is you probably need to update our saml core package as well. `composer update flipboxfactory/saml-core`.

**Comment by eheiser** [comment]
Ran the composer command but it says there is "Nothing to install or update"

**Comment by dsmrt** [comment]
@eheiser, as my commit message suggests, I missed a spot! sorry about that! Try a `composer update flipboxfactory/saml-sp`. This should update saml-sp and saml-core. Let me know if you have any issues.

**Comment by eheiser** [comment]
still says "nothing to install or update" - should I run this command in a particular directory?

**Comment by dsmrt** [comment]
I bet it has something to do with the composer.json constraints on the plugin. Try `composer require "flipboxfactory/saml-sp:^2.1"` and see if that works for you. If not, try `composer clear-cache` then try the require or update again.

**Comment by eheiser** [comment]
that did it, update went through. I have to convene with another dev to continue, will keep you posted of any progess. Thanks already!

**Comment by dsmrt** [comment]
Let me know how this goes! Closing this for now but feel free to comment here or hit me up on twitter if needed.
