### ISSUE TITLE
Craft 3.4 / AssertionConsumerServiceUrl missing in AuthNRequest

### ISSUE THREAD

**Issue by thkus** [flipboxfactory/saml-sp#58]
Hey there,

first of all: great plugin! Makes working with SAML really smooth and seamless!

I'm having troubles currently to connect with an IDP. The Response from the IDP that indicates, that AssertionConsumerServiceUrl is expected but not present. And indeed, i don't see that field in the AuthNRequest. 

If i'm not mistaken, it should be set here: https://github.com/flipboxfactory/saml-sp/blob/master/src/services/messages/AuthnRequest.php#L70

Is this correct? Or is there another way to add this value?

Many thanks!

**Comment by dsmrt** [comment]
Good find! I have a patch up in 2.1.6.

**Comment by thkus** [comment]
Works! Thanks a lot for the quick fix.
