### ISSUE TITLE
Could not find package

### ISSUE THREAD

**Issue by m8i** [flipboxfactory/saml-sp#6]
When I run

`composer require flipboxfactory/saml-sp`

I get the error

```
[InvalidArgumentException]
Could not find the package flipboxfactory/saml-sp.

Did you mean this?
    flipboxfactory/saml-sp
```

I'm not sure how to fix it since it's offering the same package as a suggestion for the one I'm looking for.

**Comment by nateiler** [comment]
Sorry to hear that.  I just ran the command and it worked as expected for me.

I would
1) check your internet connection; including behind a VPN which could be blocking it.
2) check your local host file to see if there is any strange routing going on
3) try, try again.... perhaps composer was experiencing a brief issue

```bash
Nates-MacBook-Pro% composer require flipboxfactory/saml-sp --dev
Using version ^1.0@beta for flipboxfactory/saml-sp
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 6 installs, 0 updates, 0 removals
  - Installing flipboxfactory/keychain (1.0.0-beta.7): Downloading (100%)
  - Installing symfony/http-foundation (v3.3.6): Loading from cache
  - Installing robrichards/xmlseclibs (3.0.1): Loading from cache
  - Installing lightsaml/lightsaml (1.4.1): Loading from cache
  - Installing flipboxfactory/saml-core (1.0.0-beta.8): Downloading (100%)
  - Installing flipboxfactory/saml-sp (1.0.0-beta.8): Downloading (100%)
lightsaml/lightsaml suggests installing lightsaml/symfony-bridge (Symfony 2 build container bridge)
lightsaml/lightsaml suggests installing lightsaml/sp-bundle (Symfony 2 SP security bundle)
Writing lock file
Generating optimized autoload files
```

**Comment by dsmrt** [comment]
Hi @m8i !
This might be a documentation issue. I've been testing this with new installs just now. The plugin is still in "beta" so you try adding `"minimum-stability":"beta"` to the root of your composer.json and see if that helps. This is how I've been working with this so far. Here are the docs on the `minimum-stability` setting: [https://getcomposer.org/doc/04-schema.md#minimum-stability](https://getcomposer.org/doc/04-schema.md#minimum-stability) 

Let me know if this helps.

**Comment by dsmrt** [comment]
Haven't heard back. Going to close this issue. We can reopen if needed.

**Comment by m8i** [comment]
That did the trick. My apologies... I was on vacation last week. Thanks so much for your help!
