### ISSUE TITLE
[Question] Is this SSO plugin for Craft’s admin control panel?

### ISSUE THREAD

**Issue by sidm1983** [flipboxfactory/saml-sp#61]
Hi,

I am looking to potentially use craft cms for a large enterprise and was wondering if this SSO plugin is to allow single sign on to Craft’s admin control panel or if it is used to enable SSO login for the front-end website built on top of craft cms? I need it to work for SSO into the admin control panel.

Also, will this plugin work with Azure AD B2C? Azure AD B2C supports SAML 2.0 so it should work, but just checking in case there are compatibility issues with Azure AD B2C. Apologies if these are stupid questions. I am new to craft cms and just wanted to make sure.

Thank you.

**Comment by dsmrt** [comment]
Hi @sidm1983 👋 

Not stupid questions at all! These are great questions (some exposing issues with our docs).

1. As for permissions to the control panel, I just added some docs around groups. Take a look and let me know if you need any clarification there. See https://saml-sp.flipboxfactory.com/configure/settings.html#group-configuration-group-assignment
2. With Azure AD B2C, as long as this service supports SAML 2.0, you should be fine but sometimes IdPs do some weird stuff so you may just have to test it out. Let me know if you have any questions.

Hope this helps!
