### ISSUE TITLE
Non ASCII characters in user group names

### ISSUE THREAD

**Issue by lars-at-nxc** [flipboxfactory/saml-sp#65]
Hi!

I have a issue with non ASCII characters (e.g. æ,ø,å) in the user group names.
Craft will not allow these in the user group handle.
Is it possible to translit UTF-8 to ASCII here?

Perhaps it can be a setting to specify character mappings to be perform.

Best regards
Lars

**Comment by dsmrt** [comment]
We are looking at a fix for this. We might be able to get the character mapping in too. Looking to get something out for the fix by the end of this week.

**Comment by dsmrt** [comment]
I think we are going to run the handle through this: `\Craft\StringHelper::toAscii`

**Comment by dsmrt** [comment]
Alright, that did seem to fix the issue. I added some error logging there too just incase there are any issues with conflicts with existing groups. (I was seeing this while testing.)

Tagged in https://github.com/flipboxfactory/saml-sp/releases/tag/2.1.10

**Comment by fugelset** [comment]
Thanks a lot!
It works like a charm :-)
