### ISSUE TITLE
EVENT_AFTER_RESPONSE_TO_USER not triggered

### ISSUE THREAD

**Issue by dennismeissner** [flipboxfactory/saml-sp#79]
hi @dsmrt,

i found a critical bug in your code. There is copy paste bug in Line 71. You are firing the EVENT_BEFORE_RESPONSE_TO_USER twice. The EVENT_AFTER_RESPONSE_TO_USER isn't fired anymore. This leads to users not being assigned to any groups in my case at the moment.

https://github.com/flipboxfactory/saml-sp/blob/ff443528b72434cc8782925e4eb3e9b180e40715/src/services/Login.php#L71

**Comment by dsmrt** [comment]
Good catch. Sorry about that. I have a patch up in https://github.com/flipboxfactory/saml-sp/releases/tag/2.4.1.

**Comment by dennismeissner** [comment]
Thanks again for your quick help
