### ISSUE TITLE
What are the server requirements?

### ISSUE THREAD

**Issue by bliswebagency** [flipboxfactory/saml-sp#82]
We have a client who wants SSO with ADFS. Their Craft site is on an Ubuntu server.

Do I have to start talking to them about moving to Azure or will SAML-SP "just work"?

**Comment by dsmrt** [comment]
There are no special server requirements for the plugin. Craft CMS requirements are sufficient so ubuntu OS shouldn't be a problem. 

As for ADFS implementation, reference https://github.com/flipboxfactory/saml-sp/issues/37#issuecomment-537633890

Let me know if you have any questions.

**Comment by bliswebagency** [comment]
Great news. Thanks for your help.
