### ISSUE TITLE
Control Panel - Enter your password to continue respond as incorrect

### ISSUE THREAD

**Issue by Mmasson-01** [flipboxfactory/saml-sp#86]
Plugin version : "flipboxfactory/saml-sp": "2.4.1",
CraftCMS version :  "craftcms/cms": "3.5.9",

1. Granting admin access to the Admin Panel of the CMS
2. Logging in to the Admin Panel with the SAML Service Provider option
3. Trying an admin action
4. Craft asks to Enter your password to continue.
5. Entering the same password used to authenticate through the plugin
6. Responding with incorrect password

![image](https://user-images.githubusercontent.com/39672866/96152675-cd013580-0eda-11eb-97e0-7133473c4fa4.png)

I've looked through the documentation and I can't quite figure out if it's simply not implemented or it's a miss configuration on my side.

Seems like the auth through the plugin is not fired when being prompt to enter account password while doing an admin action in the Admin Panel

**Comment by dsmrt** [comment]
This is a known issue (see #52). Craft doesn't make this too easy to override. Please add any comments to #52. Closing this.

**Comment by 7ochem** [comment]
I have this exact same issue. The users that have logged in through SAML don't have a password. You're referencing #52, but that is a quite big issue. The only issue I have is this 👆🏻

**Comment by dsmrt** [comment]
:wave: @7ochem , 

Out of everything with #52, this is the hardest part. I agree, it'd be nice to get something out here. I'll see what we can do.

**Comment by dsmrt** [comment]
Elevated Session is still a problem (the login modal in the cp). There's a lot that'd go into fixing this including ui changes on the user element and overwriting the set password functionality. There just isn't support for a lot of these changes without doing some pretty hacky fixes.

Although, it looks like you can get around the modal (asking for the password) by setting the general config item `elevatedSessionDuration` to 0 (zero).

```php
<?php
return [
   'elevatedSessionDuration' => 0,
];
```

**Comment by 7ochem** [comment]
I'll try setting `elevatedSessionDuration` to 0. Thanks for this hint!
