### ISSUE TITLE
Login page template markup is now out-of-date with Craft CMS 3.6

### ISSUE THREAD

**Issue by sidm1983** [flipboxfactory/saml-sp#95]
Hello, I recently updated a development instance of Craft CMS to version 3.6.0.1 and I noticed that the login page was slightly broken. I initially raised an issue on the craft cms github repo as I thought it was an issue with the latest version of craft. However, after a lot of investigation, I finally realised that it was the SAML SP plugin that was hijacking the login page and using its own login page markup. Basically, the login page would look a little bit broken when I have the plugin installed and would look correct when I uninstalled the plugin.

It looks like this login page markup is now out-of-date as Craft CMS has tweaked the login page HTML structure and CSS.

Please investigate and update the login page markup to be in sync with version 3.6 of Craft CMS.

Thank you 🙂

**Comment by brandonkelly** [comment]
Here’s the change: https://github.com/craftcms/cms/commit/8f037147c01dd9a78ff6e921f307c50a2cda91c3 (occurred in Craft 3.5.18).

**Comment by dsmrt** [comment]
Good catch! Thanks for pointing that out. Working on it now.

**Comment by dsmrt** [comment]
Should be good in https://github.com/flipboxfactory/saml-sp/releases/tag/2.6.1

**Please update `flipboxfactory/saml-core` to the latest as well. I found an issue with the uri that affects those login links from the cp.**

Thanks for pointing this out @sidm1983 

Also, thanks to @brandonkelly for the help!

**Comment by sidm1983** [comment]
Thank you @dsmrt for the speedy resolution!

And thank you @brandonkelly for all your help!
