### ISSUE TITLE
Bug in CP links

### ISSUE THREAD

**Issue by bs1180** [flipboxfactory/saml-sp#96]
Hey there, I'm using 2.6.1 (with Craft 3.6.4.1) and there seems to be a bug in the links in the CP.

![Screenshot 2021-02-10 at 12 21 09](https://user-images.githubusercontent.com/5904336/107503706-9098ca00-6b9a-11eb-8449-8ad48c0e22dc.png)

If I click "Staging" in this view, it instead edits the Test IDP - it seems the `/admin/saml-sp/metadata/my-provider` URL points to the wrong entity. I've worked around it by manually changing the URL to the right ID (eg. `admin/saml-sp/metadata/5`)

Thanks.

**Comment by dsmrt** [comment]
I’ll take a look.

**Comment by dsmrt** [comment]
I'm not seeing the same result on my side so this might be a config difference.

Questions:
Are you using multisite (do you have multiple sites)? 
When you go to the `my-provider` url, is that trying to create a new one or displaying one of the above (from the screenshot)?

**Comment by bs1180** [comment]
Hey, thanks for the quick response. 
- No, no multisite.
- When I go to `/my-provider` it's trying to edit the IDP, not create a new one.

**Comment by dsmrt** [comment]
Sorry for more questions but still trying to figure this out ...

1. Do you have any sites configured like a default site?
2. Is the CP admin site domain different than the public site url?
3. Is your test IdP domain the same as the SP? (I'm wondering if this is it)

**Comment by dsmrt** [comment]
I'm not sure if this was an issue but I did change the links to be more explicit, which might help. See this change in 2.6.6. Let me know how this works for you.

**Comment by bs1180** [comment]
Thanks, I think I had just misconfigured it - on a clean install it's working properly.

**Comment by dsmrt** [comment]
Awesome! Thanks for the update.
