### ISSUE TITLE
Potential bug with getNameID

### ISSUE THREAD

**Issue by andrewfairlie** [flipboxfactory/saml-sp#99]
I'm new to SSO so this might not be a bug on your side, but I'll report what I'm seeing in case it is.

I'm using the `Username/NameID Override` feature to override to an email address, and when I go to login I see that it creates the user correctly, but then on the frontend I get a Craft PHP error 

```
Call to a member function getValue() on null
```

![image](https://user-images.githubusercontent.com/1772888/109164462-60445480-7772-11eb-93f0-10a88ecf2300.png)

I think this might be where the code is looking for the `nameID` even though I'm overriding it. Is that possibly a bug? Or am I misunderstanding?

**Comment by andrewfairlie** [comment]
If this helps at all, and I'm not sure if this is a good solution but I managed to hack something together by changing https://github.com/flipboxfactory/saml-sp/blob/master/src/services/ProviderIdentity.php#L53-L59 to...

```php
        $firstAssertion = $this->getFirstAssertion($response, $serviceProvider);
        $nameIdOverride = $idpProvider->nameIdOverride;
        if ($nameIdOverride) {
            // use override
            $attributes = $firstAssertion->getAttributes();
            if (isset($attributes[$nameIdOverride])) {
                $nameID = $attributes[$nameIdOverride][0];
            }
        } else {
            $nameID = $firstAssertion->getNameID()->getValue();
        }

        // Get Identity
        $identity = $this->forceGet(
            $nameID,
            $idpProvider
        );

```

**Comment by dsmrt** [comment]
Just off the top of my head, I believe I still needs the NameID to exist but your patch might work fine. Let me look this over and think about it a little bit and see if this would work ok.

**Comment by andrewfairlie** [comment]
Hi @dsmrt this looks promising! I just need to get something from my client in order to test this fully, but I'll report back as soon as I have it :)

**Comment by andrewfairlie** [comment]
Hi @dsmrt yes this works perfectly now, thank you.
